# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: False

MATRICES:
  - file_name: autoairporttrips.san_ea_low.omx
    tables:
      - name: SOV_EA
        data_field: DRIVEALONE_EA_LOW
      - name: SR2_EA
        data_field: SHARED2_EA_LOW
      - name: SR3_EA
        data_field: SHARED3_EA_LOW
  - file_name: autoairporttrips.san_ea_med.omx
    tables:
      - name: SOV_EA
        data_field: DRIVEALONE_EA_MED
      - name: SR2_EA
        data_field: SHARED2_EA_MED
      - name: SR3_EA
        data_field: SHARED3_EA_MED
  - file_name: autoairporttrips.san_ea_high.omx
    tables:
      - name: SOV_EA
        data_field: DRIVEALONE_EA_HIGH
      - name: SR2_EA
        data_field: SHARED2_EA_HIGH
      - name: SR3_EA
        data_field: SHARED3_EA_HIGH
  - file_name: tranairporttrips.san_ea.omx
    tables:
      - name: WALK_TRANSIT_EA
        data_field: WALK_TRANSIT_EA
      - name: KNR_LOCOUT_EA
        data_field: KNR_LOCOUT_EA
      - name: KNR_PRMOUT_EA
        data_field: KNR_PRMOUT_EA        
      - name: KNR_MIXOUT_EA
        data_field: KNR_MIXOUT_EA        
      - name: TNC_LOCOUT_EA
        data_field: TNC_LOCOUT_EA
      - name: TNC_PRMOUT_EA
        data_field: TNC_PRMOUT_EA        
      - name: TNC_MIXOUT_EA
        data_field: TNC_MIXOUT_EA        
      - name: KNR_LOCIN_EA
        data_field: KNR_LOCIN_EA
      - name: KNR_PRMIN_EA
        data_field: KNR_PRMIN_EA        
      - name: KNR_MIXIN_EA
        data_field: KNR_MIXIN_EA        
      - name: TNC_LOCIN_EA
        data_field: TNC_LOCIN_EA
      - name: TNC_PRMIN_EA
        data_field: TNC_PRMIN_EA        
      - name: TNC_MIXIN_EA
        data_field: TNC_MIXIN_EA        
  - file_name: nmotairporttrips.san_ea.omx
    tables:
      - name: WALK_EA
        data_field: WALK_EA
        
  - file_name: autoairporttrips.san_am_low.omx
    tables:
      - name: SOV_AM
        data_field: DRIVEALONE_AM_LOW
      - name: SR2_AM
        data_field: SHARED2_AM_LOW
      - name: SR3_AM
        data_field: SHARED3_AM_LOW
  - file_name: autoairporttrips.san_am_med.omx
    tables:
      - name: SOV_AM
        data_field: DRIVEALONE_AM_MED
      - name: SR2_AM
        data_field: SHARED2_AM_MED
      - name: SR3_AM
        data_field: SHARED3_AM_MED
  - file_name: autoairporttrips.san_am_high.omx
    tables:
      - name: SOV_AM
        data_field: DRIVEALONE_AM_HIGH
      - name: SR2_AM
        data_field: SHARED2_AM_HIGH
      - name: SR3_AM
        data_field: SHARED3_AM_HIGH
  - file_name: tranairporttrips.san_am.omx
    tables:
      - name: WALK_TRANSIT_AM
        data_field: WALK_TRANSIT_AM
      - name: KNR_LOCOUT_AM
        data_field: KNR_LOCOUT_AM
      - name: KNR_PRMOUT_AM
        data_field: KNR_PRMOUT_AM        
      - name: KNR_MIXOUT_AM
        data_field: KNR_MIXOUT_AM        
      - name: TNC_LOCOUT_AM
        data_field: TNC_LOCOUT_AM
      - name: TNC_PRMOUT_AM
        data_field: TNC_PRMOUT_AM        
      - name: TNC_MIXOUT_AM
        data_field: TNC_MIXOUT_AM        
      - name: KNR_LOCIN_AM
        data_field: KNR_LOCIN_AM
      - name: KNR_PRMIN_AM
        data_field: KNR_PRMIN_AM        
      - name: KNR_MIXIN_AM
        data_field: KNR_MIXIN_AM        
      - name: TNC_LOCIN_AM
        data_field: TNC_LOCIN_AM
      - name: TNC_PRMIN_AM
        data_field: TNC_PRMIN_AM        
      - name: TNC_MIXIN_AM
        data_field: TNC_MIXIN_AM        
  - file_name: nmotairporttrips.san_am.omx
    tables:
      - name: WALK_AM
        data_field: WALK_AM

  - file_name: autoairporttrips.san_md_low.omx
    tables:
      - name: SOV_MD
        data_field: DRIVEALONE_MD_LOW
      - name: SR2_MD
        data_field: SHARED2_MD_LOW
      - name: SR3_MD
        data_field: SHARED3_MD_LOW
  - file_name: autoairporttrips.san_md_med.omx
    tables:
      - name: SOV_MD
        data_field: DRIVEALONE_MD_MED
      - name: SR2_MD
        data_field: SHARED2_MD_MED
      - name: SR3_MD
        data_field: SHARED3_MD_MED
  - file_name: autoairporttrips.san_md_high.omx
    tables:
      - name: SOV_MD
        data_field: DRIVEALONE_MD_HIGH
      - name: SR2_MD
        data_field: SHARED2_MD_HIGH
      - name: SR3_MD
        data_field: SHARED3_MD_HIGH
  - file_name: tranairporttrips.san_md.omx
    tables:
      - name: WALK_TRANSIT_MD
        data_field: WALK_TRANSIT_MD
      - name: KNR_LOCOUT_MD
        data_field: KNR_LOCOUT_MD
      - name: KNR_PRMOUT_MD
        data_field: KNR_PRMOUT_MD        
      - name: KNR_MIXOUT_MD
        data_field: KNR_MIXOUT_MD        
      - name: TNC_LOCOUT_MD
        data_field: TNC_LOCOUT_MD
      - name: TNC_PRMOUT_MD
        data_field: TNC_PRMOUT_MD        
      - name: TNC_MIXOUT_MD
        data_field: TNC_MIXOUT_MD        
      - name: KNR_LOCIN_MD
        data_field: KNR_LOCIN_MD
      - name: KNR_PRMIN_MD
        data_field: KNR_PRMIN_MD        
      - name: KNR_MIXIN_MD
        data_field: KNR_MIXIN_MD        
      - name: TNC_LOCIN_MD
        data_field: TNC_LOCIN_MD
      - name: TNC_PRMIN_MD
        data_field: TNC_PRMIN_MD        
      - name: TNC_MIXIN_MD
        data_field: TNC_MIXIN_MD        
  - file_name: nmotairporttrips.san_md.omx
    tables:
      - name: WALK_MD
        data_field: WALK_MD

  - file_name: autoairporttrips.san_pm_low.omx
    tables:
      - name: SOV_PM
        data_field: DRIVEALONE_PM_LOW
      - name: SR2_PM
        data_field: SHARED2_PM_LOW
      - name: SR3_PM
        data_field: SHARED3_PM_LOW
  - file_name: autoairporttrips.san_pm_med.omx
    tables:
      - name: SOV_PM
        data_field: DRIVEALONE_PM_MED
      - name: SR2_PM
        data_field: SHARED2_PM_MED
      - name: SR3_PM
        data_field: SHARED3_PM_MED
  - file_name: autoairporttrips.san_pm_high.omx
    tables:
      - name: SOV_PM
        data_field: DRIVEALONE_PM_HIGH
      - name: SR2_PM
        data_field: SHARED2_PM_HIGH
      - name: SR3_PM
        data_field: SHARED3_PM_HIGH
  - file_name: tranairporttrips.san_pm.omx
    tables:
      - name: WALK_TRANSIT_PM
        data_field: WALK_TRANSIT_PM
      - name: KNR_LOCOUT_PM
        data_field: KNR_LOCOUT_PM
      - name: KNR_PRMOUT_PM
        data_field: KNR_PRMOUT_PM        
      - name: KNR_MIXOUT_PM
        data_field: KNR_MIXOUT_PM        
      - name: TNC_LOCOUT_PM
        data_field: TNC_LOCOUT_PM
      - name: TNC_PRMOUT_PM
        data_field: TNC_PRMOUT_PM        
      - name: TNC_MIXOUT_PM
        data_field: TNC_MIXOUT_PM        
      - name: KNR_LOCIN_PM
        data_field: KNR_LOCIN_PM
      - name: KNR_PRMIN_PM
        data_field: KNR_PRMIN_PM        
      - name: KNR_MIXIN_PM
        data_field: KNR_MIXIN_PM        
      - name: TNC_LOCIN_PM
        data_field: TNC_LOCIN_PM
      - name: TNC_PRMIN_PM
        data_field: TNC_PRMIN_PM        
      - name: TNC_MIXIN_PM
        data_field: TNC_MIXIN_PM        
  - file_name: nmotairporttrips.san_pm.omx
    tables:
      - name: WALK_PM
        data_field: WALK_PM


  - file_name: autoairporttrips.san_ev_low.omx
    tables:
      - name: SOV_EV
        data_field: DRIVEALONE_EV_LOW
      - name: SR2_EV
        data_field: SHARED2_EV_LOW
      - name: SR3_EV
        data_field: SHARED3_EV_LOW
  - file_name: autoairporttrips.san_ev_med.omx
    tables:
      - name: SOV_EV
        data_field: DRIVEALONE_EV_MED
      - name: SR2_EV
        data_field: SHARED2_EV_MED
      - name: SR3_EV
        data_field: SHARED3_EV_MED
  - file_name: autoairporttrips.san_ev_high.omx
    tables:
      - name: SOV_EV
        data_field: DRIVEALONE_EV_HIGH
      - name: SR2_EV
        data_field: SHARED2_EV_HIGH
      - name: SR3_EV
        data_field: SHARED3_EV_HIGH
  - file_name: tranairporttrips.san_ev.omx
    tables:
      - name: WALK_TRANSIT_EV
        data_field: WALK_TRANSIT_EV
      - name: KNR_LOCOUT_EV
        data_field: KNR_LOCOUT_EV
      - name: KNR_PRMOUT_EV
        data_field: KNR_PRMOUT_EV        
      - name: KNR_MIXOUT_EV
        data_field: KNR_MIXOUT_EV        
      - name: TNC_LOCOUT_EV
        data_field: TNC_LOCOUT_EV
      - name: TNC_PRMOUT_EV
        data_field: TNC_PRMOUT_EV        
      - name: TNC_MIXOUT_EV
        data_field: TNC_MIXOUT_EV        
      - name: KNR_LOCIN_EV
        data_field: KNR_LOCIN_EV
      - name: KNR_PRMIN_EV
        data_field: KNR_PRMIN_EV        
      - name: KNR_MIXIN_EV
        data_field: KNR_MIXIN_EV        
      - name: TNC_LOCIN_EV
        data_field: TNC_LOCIN_EV
      - name: TNC_PRMIN_EV
        data_field: TNC_PRMIN_EV        
      - name: TNC_MIXIN_EV
        data_field: TNC_MIXIN_EV        
  - file_name: nmotairporttrips.san_ev.omx
    tables:
      - name: WALK_EV
        data_field: WALK_EV
                
        
CONSTANTS:
  time_periods:
    EA:
      first_hour: 1
      last_hour: 6
    AM:
      first_hour: 7
      last_hour: 12
    MD:
      first_hour: 13
      last_hour: 25
    PM:
      first_hour: 26
      last_hour: 32
    EV:
      first_hour: 33
      last_hour: 48
  # SHARED2 and SHARED3 Occupancies
  OCC_SHARED2: 2.0
  OCC_SHARED3: 3.33
  vot_threshold_low: 8.81
  vot_threshold_med: 18.00