#//////////////////////////////////////////////////////////////////////////////
#////                                                                       ///
#//// Copyright INRO, 2016-2017.                                            ///
#//// Rights to use and modify are granted to the                           ///
#//// San Diego Association of Governments and partner agencies.            ///
#//// This copyright notice must be preserved.                              ///
#////                                                                       ///
#//// import/import_transit_demand.py                                       ///
#////                                                                       ///
#////                                                                       ///
#////                                                                       ///
#////                                                                       ///
#//////////////////////////////////////////////////////////////////////////////

TOOLBOX_ORDER = 63


import inro.modeller as _m
import traceback as _traceback
import omx as _omx
import os


dem_utils = _m.Modeller().module('sandag.utilities.demand')
gen_utils = _m.Modeller().module("sandag.utilities.general")


class ImportMatrices(_m.Tool(), gen_utils.Snapshot):

    output_dir = _m.Attribute(unicode)
    
    tool_run_msg = ""

    @_m.method(return_type=_m.UnicodeType)
    def tool_run_msg_status(self):
        return self.tool_run_msg

    def __init__(self):
        project_dir = os.path.dirname(_m.Modeller().desktop.project.path)
        main_dir = os.path.dirname(project_dir)
        self.output_dir = os.path.join(main_dir, "output")
        self.attributes = ["output_dir"]

    def page(self):
        pb = _m.ToolPageBuilder(self)
        pb.title = "Import transit demand"
        pb.description = """ 
<div style="text-align:left">    
    Imports the trip matrices generated by CT-RAMP in OMX format, and
    adds the demand from the aggregate models for the final
    trip assignments. <br>
    A total of 50 OMX files are expected, for 5 time periods
    EA, AM, MD, PM and EV, times 5 model segments for both auto:
    <ul>
        <li>tranTrips_XX.omx</li>
        <li>tranCrossBorderTrips_XX.omx</li>
        <li>tranAirportTrips_XX.omx</li>
        <li>tranVisitorTrips_XX.omx</li>
        <li>tranInternalExternalTrips_XX.omx</li>
    </ul>
</div>
        """
        pb.branding_text = "- SANDAG - Model"

        if self.tool_run_msg != "":
            pb.tool_run_status(self.tool_run_msg_status)
        pb.add_select_file('output_dir', 'directory',
                           title='Select output directory')
        pb.add_text_box("external_zones", title="External zones:")
        dem_utils.add_select_processors("num_processors", pb, self)
        return pb.render()

    def run(self):
        self.tool_run_msg = ""
        try:
            scenario = _m.Modeller().scenario
            self(self.output_dir, self.external_zones, self.num_processors, scenario)
            run_msg = "Tool completed"
            self.tool_run_msg = _m.PageBuilder.format_info(run_msg, escape=False)
        except Exception as error:
            self.tool_run_msg = _m.PageBuilder.format_exception(
                error, _traceback.format_exc(error))
            raise

    @_m.logbook_trace("Sum demand", save_arguments=True)
    def __call__(self, output_dir, scenario):
        attributes = {"output_dir": output_dir}
        gen_utils.log_snapshot("Sum demand", str(self), attributes)

        self.scenario = scenario
        self.output_dir = output_dir
        self.import_transit_trips()

    @_m.logbook_trace("Import CT-RAMP transit trips from OMX")
    def import_transit_trips(self):
        emmebank = self.scenario.emmebank
        person = self.lookup_omx("tranTrips")
        cross_border = self.lookup_omx("tranCrossBorderTrips")
        airport = self.lookup_omx("tranAirportTrips")
        visitor = self.lookup_omx("tranVisitorTrips")
        internal_external = self.lookup_omx("tranInternalExternalTrips")
        try:
            periods = ["EA", "AM", "MD", "PM", "EV"]
            for period in periods:
                with _m.logbook_trace("Period %s" % period):
                    modes =      [
                        "WLKBUS","WLKEXP","WLKBRT","WLKLRT","WLKCMR",
                        "PNRBUS","PNREXP","PNRBRT","PNRLRT","PNRCMR",
                        "KNRBUS","KNREXP","KNRBRT","KNRLRT","KNRCMR"
                    ]
                    file_modes = [
                        "WLK_LOC","WLK_EXP","WLK_BRT","WLK_LRT","WLK_CMR",
                        "PNR_LOC","PNR_EXP","PNR_BRT","PNR_LRT","PNR_CMR",
                        "KNR_LOC","KNR_EXP","KNR_BRT","KNR_LRT","KNR_CMR"
                    ]
                    file_modes = [m + "_" + period for m in file_modes]
                    for mode, file_mode in zip(modes, file_modes):
                        with _m.logbook_trace("Import for mode %s" % mode):
                            # TODO, optional: log matrix statistics ...
                            matrix = emmebank.matrix("mf%s_%s" % (period, mode))
                            total_ct_ramp_trips = (person[period][file_mode].read()
                                                   + cross_border[period][file_mode].read()
                                                   + airport[period][file_mode].read()
                                                   + visitor[period][file_mode].read()
                                                   + internal_external[period][file_mode].read())
                            matrix.set_numpy_data(total_ct_ramp_trips, self.scenario)
        finally:
            for period in periods:
                person[period].close()
                airport[period].close()
                cross_border[period].close()
                visitor[period].close()
                internal_external[period].close()

    def lookup_omx(self, file_name):
        directory = self.output_dir
        periods = ["EA", "AM", "MD", "PM", "EV"]
        matrix_tables = {}
        for period in periods:
            file_path = os.path.join(directory, file_name + "_" + period + ".mtx")
            matrix_tables[period] = _omx.openFile(file_path, 'r')
        return matrix_tables
