set PROJECT_DRIVE=%1
set PROJECT_DIRECTORY=%2
set PROJECT_DIRECTORY_FWD=%3

%PROJECT_DRIVE%
set "SCEN_DIR=%PROJECT_DRIVE%%PROJECT_DIRECTORY%"
set "SCEN_DIR_FWD=%PROJECT_DRIVE%%PROJECT_DIRECTORY_FWD%"

cd %PROJECT_DRIVE%%PROJECT_DIRECTORY%\python
python.exe %SCEN_DIR%\python\sandag\selectLinkQueryFileCheck.py
