# misc settings
data_dir: input
config_dir: src\asim\configs\airport.cbx
# distance_param: -0.19
# walk_speed: 3


# non-skim inputs
maz_input_fname: land_use.csv
hh_input_fname: households.csv
employee_park_fname: airport_employee_park.CBX.csv
arrival_sched_probs_fname: airport_arrival.CBX.csv
departure_sched_probs_fname: airport_departure.CBX.csv
purpose_probs_input_fname: airport_purpose.CBX.csv
party_size_probs_input_fname: airport_party.CBX.csv
nights_probs_input_fname: airport_nights.CBX.csv
income_probs_input_fname: airport_income.CBX.csv
ext_station_probs_input_fname: InternalExternalDestinationChoiceAlternatives.csv
# trip_scheduling_probs_input_fnames:
  # outbound: crossBorder_outboundStopDuration.csv
  # inbound: crossBorder_inboundStopDuration.csv

#outputs
sched_probs_output_name: tour_scheduling_probs.csv
# output data
# mazs_output_fname: mazs_xborder.csv
households_output_fname: households_airport.cbx.csv
persons_output_fname: persons_airport.cbx.csv
tours_output_fname: tours_airport.cbx.csv
maz_output_fname: land_use.cbx.csv
# tap_lines_output_fname: tap_lines.csv
# taps_output_fname: taps.csv

airport_code: CBX

# output configs
tour_scheduling_probs_output_fname: tour_scheduling_probs.csv
tour_scheduling_alts_output_fname: tour_departure_and_duration_alternatives.csv
stop_frequency_alts_output_fname: stop_frequency_alternatives.csv
stop_frequency_coeffs_output_formattable_fname: 'stop_frequency_coefficients_{purpose}.csv'
stop_frequency_expressions_output_formattable_fname: 'stop_frequency_{purpose}.csv'
trip_purpose_probs_output_fname: trip_purpose_probs.csv
trip_scheduling_probs_output_fname: trip_scheduling_probs.csv

# skims
skims:
  maz_to_maz:
    walk:
      input_fname: microMgraEquivMinutes.csv
      output_fname: maz_maz_walk.csv
      rename_columns:
        i: OMAZ
        j: DMAZ
  taz_to_taz:
    periods:
      - EA
      - AM
      - MD
      - PM
      - EV
    input_base_fname: traffic_skims
    output_base_fname: traffic_skims_processed
    # output_base_fname: traffic_skims_xborder




# airport.CBX.enplanements = 9740640
# airport.CBX.connecting = 364940
# airport.CBX.annualizationFactor = 365
# airport.CBX.averageSize = 1.7
# airport.CBX.airportMgra = 2997

# airport.CBX.enplanements = 911510
# airport.CBX.connecting = 0
# airport.CBX.annualizationFactor = 365
# airport.CBX.averageSize = 2.2
# airport.CBX.airportMgra = 7061
# Tours
tours:
  num_enplanements: 4186500
  avg_party_size: 2.2
  annualization_factor: 365
  connecting: 0
  airport_mgra: 9350

