time_period: MD
time_threshold: 45
infinity: 999
outfile: report\walkMgrasWithin45Min_MD.csv

transit_skim_matrices: # If set to True, replace values of zero with the number set as infinity
  WALK_LOC_XFERWALK__{}: False
  WALK_LOC_XFERWAIT__{}: False
  WALK_LOC_TOTALIVTT__{}: True
  WALK_PRM_XFERWALK__{}: False
  WALK_PRM_XFERWAIT__{}: False
  WALK_PRM_TOTALIVTT__{}: True
  WALK_MIX_XFERWALK__{}: False
  WALK_MIX_XFERWAIT__{}: False
  WALK_MIX_TOTALIVTT__{}: True

traffic_skim_matrices: # If set to True, replace values of zero with the number set as infinity
  HOV3_M_DIST__{}: False
  HOV3_M_TIME__{}: False
  SOV_NT_L_TIME__{}: False

active_skim_files:
  walk_time: maz_maz_walk.csv
  bike_time: maz_maz_bike.csv