
enable: False

bundles:
  - tour_scheduling_probabilistic
  - non_mandatory_tour_destination
  - tour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_scheduling
  - trip_mode_choice

# NOTE: survey table indices must match 1-to-1 with input tables specified in
# settings.yaml. It is recommended to use the same files in both places, but
# this means the trip_id's in the survey data must have been created via the
# abm.models.util.canonical_ids module.
survey_tables:
  households:
    file_name: households_survey.csv
    index_col: household_id
  persons:
    file_name:  persons_survey.csv
    index_col: person_id
  tours:
    file_name:  tours_survey.csv
    index_col: tour_id
  trips:
    file_name:  trips_survey.csv
    index_col: trip_id