
SPEC: cvm_accessibility.csv

# columns from land_use table to add to df
land_use_columns: 
  - 'num_hh_food_delivery'
  - 'num_hh_package_delivery'
  - 'num_hh_service'
  - 'establishment_attraction'
  - 'establishment_attraction_group1'
  - 'establishment_attraction_group2'
  - 'establishment_attraction_group3'
  - 'establishment_attraction_group4'

establishment_acc_agg_groups:
  - name: establishment_attraction_group1
    columns:
      - establishment_attraction_ret
      - establishment_attraction_whl
      - establishment_attraction_mfg
  - name: establishment_attraction_group2
    columns:
      - establishment_attraction_iut
      - establishment_attraction_laf
  - name: establishment_attraction_group3
    columns:
      - establishment_attraction_con
      - establishment_attraction_agm
      - establishment_attraction_epo
      - establishment_attraction_mhs
      - establishment_attraction_trn
  - name: establishment_attraction_group4
    columns:
      - establishment_attraction_ifr

CONSTANTS:
  vot_light: {cvm-vot-light:} # dollar per hour
  vot_medium: {cvm-vot-medium:}
  vot_heavy: {cvm-vot-heavy:}
  vot_tnc: {cvm-vot-tnc:}
  prop_light: {cvm-weightedAverageProportions-light:}
  prop_medium: {cvm-weightedAverageProportions-medium:}
  prop_heavy: {cvm-weightedAverageProportions-heavy:}
  prop_light_tnc: {cvm-weightedAverageProportions-tnc-light:}
  prop_medium_tnc: {cvm-weightedAverageProportions-tnc-medium:}
  prop_heavy_tnc: {cvm-weightedAverageProportions-tnc-heavy:}
  decay_est: {cvm-attractionDecay:}
  dispersion_parameter_est: {cvm-attractionParameter:}
  decay_tnc_est: {cvm-tncAttractionDecay:}
  dispersion_parameter_tnc_est: {cvm-tncAttractionParameter:}