RESULT_COL_NAME: establishment_attraction

industries:
  1: 
    description: agriculture_mining
    name: AGM
    industry_factor: 1.4058
    industry_group: 3
  2: 
    description: manufacturing
    name: MFG
    industry_factor: 1.0667
    industry_group: 1
  3: 
    description: industry_utilities
    name: IUT
    industry_factor: 1.0965
    industry_group: 2
  4: 
    description: retail
    name: RET
    industry_factor: 2.0747
    industry_group: 1
  5: 
    description: wholesale
    name: WHL
    industry_factor: 1.9158
    industry_group: 1
  6: 
    description: construction
    name: CON
    industry_factor: 1.7496
    industry_group: 3
  7: 
    description: transportation
    name: TRN
    industry_factor: 1.5830
    industry_group: 3
  8: 
    description: info_finance_insurance_realestate_professional
    name: IFR
    industry_factor: 1.4600
    industry_group: 4
  9: 
    description: education_publicservices
    name: EPO
    industry_factor: 1.3284
    industry_group: 3
  10: 
    description: medical_health
    name: MHS
    industry_factor: 1.8163
    industry_group: 3
  11: 
    description: leisure_accommondation_food
    name: LAF
    industry_factor: 1.2448
    industry_group: 2

# these are the parameters for the first step in the establishment attraction model
industry_groups:
  1:
    beta_employment: 0.0219
    constant: 1.7548
  2:
    beta_employment: 0.0172
    constant: 1.3747
  3:
    beta_employment: 0.0322
    constant: 0.9198
  4:
    beta_employment: 0.027
    constant: 0.5917

CONSTANTS:
  beta_employment: 0.7051 # used in the second step of the establishment attraction model