RESULT_COL_NAME: establishment_attraction

industries:
  1: 
    description: agriculture_mining
    name: AGM
    industry_factor: 1.7347
    industry_group: 3
  2: 
    description: manufacturing
    name: MFG
    industry_factor: 1.0596
    industry_group: 1
  3: 
    description: industry_utilities
    name: IUT
    industry_factor: 1.1606
    industry_group: 2
  4: 
    description: retail
    name: RET
    industry_factor: 2.0876
    industry_group: 1
  5: 
    description: wholesale
    name: WHL
    industry_factor: 1.9118
    industry_group: 1
  6: 
    description: construction
    name: CON
    industry_factor: 1.7439
    industry_group: 3
  7: 
    description: transportation
    name: TRN
    industry_factor: 1.5510
    industry_group: 3
  8: 
    description: info_finance_insurance_realestate_professional
    name: IFR
    industry_factor: 1.4471
    industry_group: 4
  9: 
    description: education_publicservices
    name: EPO
    industry_factor: 1.3249
    industry_group: 3
  10: 
    description: medical_health
    name: MHS
    industry_factor: 1.8148
    industry_group: 3
  11: 
    description: leisure_accommondation_food
    name: LAF
    industry_factor: 1.2439
    industry_group: 2
  12: 
    description: military
    name: MIL
    industry_factor: 0
    industry_group: 5

# these are the parameters for the first step in the establishment attraction model
industry_groups:
  1:
    beta_employment: 0.0219
    constant: 1.7566
  2:
    beta_employment: 0.0172
    constant: 1.3893
  3:
    beta_employment: 0.0322
    constant: 0.9284
  4:
    beta_employment: 0.027
    constant: 0.5782
  5:
    beta_employment: 0
    constant: 99

CONSTANTS:
  beta_employment: {cvm-betaEmployment-establishmentAttractor:} # used in the second step of the establishment attraction model