SPEC: household_attractor.csv
COEFFICIENTS: household_attractor_coefficients.csv
LOGIT_TYPE: MNL
RESULT_COL_NAME: has_attraction
HAS_ATTRACTION_ALT: 0

preprocessor: 
  SPEC: household_attractor_preprocessor.csv
  DF: df
  TABLES:
    - tours

annotate_land_use:
  SPEC: annotate_land_use_hh_attractor
  DF: land_use
  TABLES:
    - households