LOGIT_TYPE: MNL

SPEC: route_vehicle_purpose_customer.csv
COEFFICIENTS: route_vehicle_purpose_customer_coefficients.csv
ALTS: route_vehicle_purpose_customer_alternatives.csv

CVM_ABM3_VEHICLE_DISTRIBUTION_FILE: cvm_abm3_vehicle_distribution.csv