SPEC: route_terminal.csv
COEFFICIENTS: route_terminal_coefficients.csv

SIZE_TERM_SELECTOR: commerce

CHOOSER_SEGMENT_COLUMN_NAME: terminal_stop_type

SEGMENTS:
  - base
  - warehouse
  - intermodal
  - residential
  - commercial

SIMULATE_CHOOSER_COLUMNS:
  - route_type
  - establishment_zone_id
  - route_id

RESULT_COL_NAME: terminal_zone

## model-specific logsum-related settings
#CHOOSER_ORIG_COL_NAME: home_zone_id
#ALT_DEST_COL_NAME: alt_dest
#OUT_PERIOD: 1