households_sample_size: 0
establishments_sample_size: 50
trace_establishment_id:
trace_hh_id: 479044

inherit_settings: True
chunk_size: 0
chunk_training_mode: disabled
input_table_list:
  - tablename: households
    filename: final_households.csv
    index_col: household_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
      - sample_rate
      - num_adults
      - num_nonworker_adults
      - num_children
  - tablename: establishments
    filename: SynthEstablishments_BaseYr_2023-11-02.csv
    index_col: establishment_id
    rename_columns:
      Industry_No: industry_number
      Industry_Name: industry_name
      MGRA: zone_id
      Employees: employees
      Size_Class: size_class
  - tablename: land_use
    filename: final_land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
    drop_columns:
      - i1
      - i2
      - i3
      - i4
      - i5
      - i6
      - i7
      - i8
      - i9
      - hs
      - hs_sf
      - hs_mf
      - hs_mh
      - hh_sf
      - hh_mf
      - hh_mh
      - zip09
      - luz_id
  - tablename: tours
    filename: final_tours.csv
    index_col: tour_id
    keep_columns:
      - household_id
      - primary_purpose
      - tour_category
      - tour_type
  - tablename: persons
    filename: final_persons.csv
    index_col: person_id
    keep_columns:
      - household_id
      - age

output_tables:
 h5_store: False
 action: include
 prefix: cvm_
 sort: True
 tables:
   - commercial_accessibility
   - land_use
   - households
   - routes
   - cv_trips
   - establishments


models:
  - household_attractor
  - establishment_attractor
  - cvm_accessibility
  - route_generation
  - route_purpose_and_vehicle
  - route_origination_type
  - route_origination
  - route_terminal_type
  - route_terminal
  - route_start_time
  - route_stops
  - write_cvm_trip_matrices
  - write_tables

