inherit_settings: True

zone_system: 2

skim_dict_factory: NumpyArraySkimFactory
#skim_dict_factory: MemMapSkimFactory

# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: False
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: False

taz_skims: 
  - traffic_skims*.omxz
  - transit_skims*.omxz
  - dest_pmsa.omx
  - dest_poi.omx

maz: mazs_xborder.csv   # mgra.csv

maz_to_maz:
  tables:
    - maz_maz_walk.csv   # microMgraEquivMinutes.csv

skim_time_periods:
    time_window: 1440
    period_minutes: 30
    periods: [0, 6, 12, 25, 32, 48]  # asim xborder
    # periods: [0, 3, 9, 22, 29, 48]  # ctramp xborder
    labels: &skim_time_period_labels ['EA', 'AM', 'MD', 'PM', 'EV']
 


