model_name: crossborder

output_tables:
  h5_store: False
  action: include
  prefix: final_
  # FIXME sort is an undocumented feature - sorts table by best index or ref_col according to traceable_table_indexes
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips

resume_after: write_trip_matrices

models:
  - write_trip_matrices
  - write_to_datalake