# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours
    - persons
TOURS_MERGED_CHOOSER_COLUMNS:
  - work_time_factor
  - non_work_time_factor
  - tour_type

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: True

MATRICES:
  - file_name: autoCrossborderTrips_EA_low.omx
    tables:
      - name: SR2_EA
        data_field: SHARED2_EA_low
      - name: SR3_EA
        data_field: SHARED3_EA_low
      - name: SOV_EA
        data_field: DRIVEALONE_EA_low
  - file_name: autoCrossborderTrips_EA_med.omx
    tables:
      - name: SR2_EA
        data_field: SHARED2_EA_med
      - name: SR3_EA
        data_field: SHARED3_EA_med
      - name: SOV_EA
        data_field: DRIVEALONE_EA_med
  - file_name: autoCrossborderTrips_EA_high.omx
    tables:
      - name: SR2_EA
        data_field: SHARED2_EA_high
      - name: SR3_EA
        data_field: SHARED3_EA_high
      - name: SOV_EA
        data_field: DRIVEALONE_EA_high
  - file_name: tranCrossborderTrips_EA.omx
    tables:
      - name: WALK_SET_set1_EA
        data_field: WALK_SET_set1_EA
      - name: WALK_SET_set2_EA
        data_field: WALK_SET_set2_EA
      - name: WALK_SET_set3_EA
        data_field: WALK_SET_set3_EA
      - name: PNRIN_SET_set1_EA
        data_field: PNRIN_SET_set1_EA
      - name: PNRIN_SET_set2_EA
        data_field: PNRIN_SET_set2_EA
      - name: PNRIN_SET_set3_EA
        data_field: PNRIN_SET_set3_EA
      - name: KNRIN_SET_set1_EA
        data_field: KNRIN_SET_set1_EA
      - name: KNRIN_SET_set2_EA
        data_field: KNRIN_SET_set2_EA
      - name: KNRIN_SET_set3_EA
        data_field: KNRIN_SET_set3_EA
      - name: TNCIN_SET_set1_EA
        data_field: TNCIN_SET_set1_EA
      - name: TNCIN_SET_set2_EA
        data_field: TNCIN_SET_set2_EA
      - name: TNCIN_SET_set3_EA
        data_field: TNCIN_SET_set3_EA
      - name: PNROUT_SET_set1_EA
        data_field: PNROUT_SET_set1_EA
      - name: PNROUT_SET_set2_EA
        data_field: PNROUT_SET_set2_EA
      - name: PNROUT_SET_set3_EA
        data_field: PNROUT_SET_set3_EA
      - name: KNROUT_SET_set1_EA
        data_field: KNROUT_SET_set1_EA
      - name: KNROUT_SET_set2_EA
        data_field: KNROUT_SET_set2_EA
      - name: KNROUT_SET_set3_EA
        data_field: KNROUT_SET_set3_EA
      - name: TNCOUT_SET_set1_EA
        data_field: TNCOUT_SET_set1_EA
      - name: TNCOUT_SET_set2_EA
        data_field: TNCOUT_SET_set2_EA
      - name: TNCOUT_SET_set3_EA
        data_field: TNCOUT_SET_set3_EA
  - file_name: othrCrossborderTrips_EA.omx
    tables:
      - name: TAXI_EA
        data_field: TAXI_EA
      - name: TNC_SINGLE_EA
        data_field: TNC_SINGLE_EA
      - name: TNC_SHARED_EA
        data_field: TNC_SHARED_EA
  - file_name: nmCrossborderTrips_EA.omx
    tables:
      - name: WALK_EA
        data_field: WALK_EA
      - name: BIKE_EA
        data_field: BIKE_EA
  - file_name: autoCrossborderTrips_AM_low.omx
    tables:
      - name: SR2_AM
        data_field: SHARED2_AM_low
      - name: SR3_AM
        data_field: SHARED3_AM_low
      - name: SOV_AM
        data_field: DRIVEALONE_AM_low
  - file_name: autoCrossborderTrips_AM_med.omx
    tables:
      - name: SR2_AM
        data_field: SHARED2_AM_med
      - name: SR3_AM
        data_field: SHARED3_AM_med
      - name: SOV_AM
        data_field: DRIVEALONE_AM_med
  - file_name: autoCrossborderTrips_AM_high.omx
    tables:
      - name: SR2_AM
        data_field: SHARED2_AM_high
      - name: SR3_AM
        data_field: SHARED3_AM_high
      - name: SOV_AM
        data_field: DRIVEALONE_AM_high
  - file_name: tranCrossborderTrips_AM.omx
    tables:
      - name: WALK_SET_set1_AM
        data_field: WALK_SET_set1_AM
      - name: WALK_SET_set2_AM
        data_field: WALK_SET_set2_AM
      - name: WALK_SET_set3_AM
        data_field: WALK_SET_set3_AM
      - name: PNRIN_SET_set1_AM
        data_field: PNRIN_SET_set1_AM
      - name: PNRIN_SET_set2_AM
        data_field: PNRIN_SET_set2_AM
      - name: PNRIN_SET_set3_AM
        data_field: PNRIN_SET_set3_AM
      - name: KNRIN_SET_set1_AM
        data_field: KNRIN_SET_set1_AM
      - name: KNRIN_SET_set2_AM
        data_field: KNRIN_SET_set2_AM
      - name: KNRIN_SET_set3_AM
        data_field: KNRIN_SET_set3_AM
      - name: TNCIN_SET_set1_AM
        data_field: TNCIN_SET_set1_AM
      - name: TNCIN_SET_set2_AM
        data_field: TNCIN_SET_set2_AM
      - name: TNCIN_SET_set3_AM
        data_field: TNCIN_SET_set3_AM
      - name: PNROUT_SET_set1_AM
        data_field: PNROUT_SET_set1_AM
      - name: PNROUT_SET_set2_AM
        data_field: PNROUT_SET_set2_AM
      - name: PNROUT_SET_set3_AM
        data_field: PNROUT_SET_set3_AM
      - name: KNROUT_SET_set1_AM
        data_field: KNROUT_SET_set1_AM
      - name: KNROUT_SET_set2_AM
        data_field: KNROUT_SET_set2_AM
      - name: KNROUT_SET_set3_AM
        data_field: KNROUT_SET_set3_AM
      - name: TNCOUT_SET_set1_AM
        data_field: TNCOUT_SET_set1_AM
      - name: TNCOUT_SET_set2_AM
        data_field: TNCOUT_SET_set2_AM
      - name: TNCOUT_SET_set3_AM
        data_field: TNCOUT_SET_set3_AM
  - file_name: othrCrossborderTrips_AM.omx
    tables:
      - name: TAXI_AM
        data_field: TAXI_AM
      - name: TNC_SINGLE_AM
        data_field: TNC_SINGLE_AM
      - name: TNC_SHARED_AM
        data_field: TNC_SHARED_AM
  - file_name: nmCrossborderTrips_AM.omx
    tables:
      - name: WALK_AM
        data_field: WALK_AM
      - name: BIKE_AM
        data_field: BIKE_AM
  - file_name: autoCrossborderTrips_MD_low.omx
    tables:
      - name: SR2_MD
        data_field: SHARED2_MD_low
      - name: SR3_MD
        data_field: SHARED3_MD_low
      - name: SOV_MD
        data_field: DRIVEALONE_MD_low
  - file_name: autoCrossborderTrips_MD_med.omx
    tables:
      - name: SR2_MD
        data_field: SHARED2_MD_med
      - name: SR3_MD
        data_field: SHARED3_MD_med
      - name: SOV_MD
        data_field: DRIVEALONE_MD_med
  - file_name: autoCrossborderTrips_MD_high.omx
    tables:
      - name: SR2_MD
        data_field: SHARED2_MD_high
      - name: SR3_MD
        data_field: SHARED3_MD_high
      - name: SOV_MD
        data_field: DRIVEALONE_MD_high
  - file_name: tranCrossborderTrips_MD.omx
    tables:
      - name: WALK_SET_set1_MD
        data_field: WALK_SET_set1_MD
      - name: WALK_SET_set2_MD
        data_field: WALK_SET_set2_MD
      - name: WALK_SET_set3_MD
        data_field: WALK_SET_set3_MD
      - name: PNRIN_SET_set1_MD
        data_field: PNRIN_SET_set1_MD
      - name: PNRIN_SET_set2_MD
        data_field: PNRIN_SET_set2_MD
      - name: PNRIN_SET_set3_MD
        data_field: PNRIN_SET_set3_MD
      - name: KNRIN_SET_set1_MD
        data_field: KNRIN_SET_set1_MD
      - name: KNRIN_SET_set2_MD
        data_field: KNRIN_SET_set2_MD
      - name: KNRIN_SET_set3_MD
        data_field: KNRIN_SET_set3_MD
      - name: TNCIN_SET_set1_MD
        data_field: TNCIN_SET_set1_MD
      - name: TNCIN_SET_set2_MD
        data_field: TNCIN_SET_set2_MD
      - name: TNCIN_SET_set3_MD
        data_field: TNCIN_SET_set3_MD
      - name: PNROUT_SET_set1_MD
        data_field: PNROUT_SET_set1_MD
      - name: PNROUT_SET_set2_MD
        data_field: PNROUT_SET_set2_MD
      - name: PNROUT_SET_set3_MD
        data_field: PNROUT_SET_set3_MD
      - name: KNROUT_SET_set1_MD
        data_field: KNROUT_SET_set1_MD
      - name: KNROUT_SET_set2_MD
        data_field: KNROUT_SET_set2_MD
      - name: KNROUT_SET_set3_MD
        data_field: KNROUT_SET_set3_MD
      - name: TNCOUT_SET_set1_MD
        data_field: TNCOUT_SET_set1_MD
      - name: TNCOUT_SET_set2_MD
        data_field: TNCOUT_SET_set2_MD
      - name: TNCOUT_SET_set3_MD
        data_field: TNCOUT_SET_set3_MD
  - file_name: othrCrossborderTrips_MD.omx
    tables:
      - name: TAXI_MD
        data_field: TAXI_MD
      - name: TNC_SINGLE_MD
        data_field: TNC_SINGLE_MD
      - name: TNC_SHARED_MD
        data_field: TNC_SHARED_MD
  - file_name: nmCrossborderTrips_MD.omx
    tables:
      - name: WALK_MD
        data_field: WALK_MD
      - name: BIKE_MD
        data_field: BIKE_MD
  - file_name: autoCrossborderTrips_PM_low.omx
    tables:
      - name: SR2_PM
        data_field: SHARED2_PM_low
      - name: SR3_PM
        data_field: SHARED3_PM_low
      - name: SOV_PM
        data_field: DRIVEALONE_PM_low
  - file_name: autoCrossborderTrips_PM_med.omx
    tables:
      - name: SR2_PM
        data_field: SHARED2_PM_med
      - name: SR3_PM
        data_field: SHARED3_PM_med
      - name: SOV_PM
        data_field: DRIVEALONE_PM_med
  - file_name: autoCrossborderTrips_PM_high.omx
    tables:
      - name: SR2_PM
        data_field: SHARED2_PM_high
      - name: SR3_PM
        data_field: SHARED3_PM_high
      - name: SOV_PM
        data_field: DRIVEALONE_PM_high
  - file_name: tranCrossborderTrips_PM.omx
    tables:
      - name: WALK_SET_set1_PM
        data_field: WALK_SET_set1_PM
      - name: WALK_SET_set2_PM
        data_field: WALK_SET_set2_PM
      - name: WALK_SET_set3_PM
        data_field: WALK_SET_set3_PM
      - name: PNRIN_SET_set1_PM
        data_field: PNRIN_SET_set1_PM
      - name: PNRIN_SET_set2_PM
        data_field: PNRIN_SET_set2_PM
      - name: PNRIN_SET_set3_PM
        data_field: PNRIN_SET_set3_PM
      - name: KNRIN_SET_set1_PM
        data_field: KNRIN_SET_set1_PM
      - name: KNRIN_SET_set2_PM
        data_field: KNRIN_SET_set2_PM
      - name: KNRIN_SET_set3_PM
        data_field: KNRIN_SET_set3_PM
      - name: TNCIN_SET_set1_PM
        data_field: TNCIN_SET_set1_PM
      - name: TNCIN_SET_set2_PM
        data_field: TNCIN_SET_set2_PM
      - name: TNCIN_SET_set3_PM
        data_field: TNCIN_SET_set3_PM
      - name: PNROUT_SET_set1_PM
        data_field: PNROUT_SET_set1_PM
      - name: PNROUT_SET_set2_PM
        data_field: PNROUT_SET_set2_PM
      - name: PNROUT_SET_set3_PM
        data_field: PNROUT_SET_set3_PM
      - name: KNROUT_SET_set1_PM
        data_field: KNROUT_SET_set1_PM
      - name: KNROUT_SET_set2_PM
        data_field: KNROUT_SET_set2_PM
      - name: KNROUT_SET_set3_PM
        data_field: KNROUT_SET_set3_PM
      - name: TNCOUT_SET_set1_PM
        data_field: TNCOUT_SET_set1_PM
      - name: TNCOUT_SET_set2_PM
        data_field: TNCOUT_SET_set2_PM
      - name: TNCOUT_SET_set3_PM
        data_field: TNCOUT_SET_set3_PM
  - file_name: othrCrossborderTrips_PM.omx
    tables:
      - name: TAXI_PM
        data_field: TAXI_PM
      - name: TNC_SINGLE_PM
        data_field: TNC_SINGLE_PM
      - name: TNC_SHARED_PM
        data_field: TNC_SHARED_PM
  - file_name: nmCrossborderTrips_PM.omx
    tables:
      - name: WALK_PM
        data_field: WALK_PM
      - name: BIKE_PM
        data_field: BIKE_PM
  - file_name: autoCrossborderTrips_EV_low.omx
    tables:
      - name: SR2_EV
        data_field: SHARED2_EV_low
      - name: SR3_EV
        data_field: SHARED3_EV_low
      - name: SOV_EV
        data_field: DRIVEALONE_EV_low
  - file_name: autoCrossborderTrips_EV_med.omx
    tables:
      - name: SR2_EV
        data_field: SHARED2_EV_med
      - name: SR3_EV
        data_field: SHARED3_EV_med
      - name: SOV_EV
        data_field: DRIVEALONE_EV_med
  - file_name: autoCrossborderTrips_EV_high.omx
    tables:
      - name: SR2_EV
        data_field: SHARED2_EV_high
      - name: SR3_EV
        data_field: SHARED3_EV_high
      - name: SOV_EV
        data_field: DRIVEALONE_EV_high
  - file_name: tranCrossborderTrips_EV.omx
    tables:
      - name: WALK_SET_set1_EV
        data_field: WALK_SET_set1_EV
      - name: WALK_SET_set2_EV
        data_field: WALK_SET_set2_EV
      - name: WALK_SET_set3_EV
        data_field: WALK_SET_set3_EV
      - name: PNRIN_SET_set1_EV
        data_field: PNRIN_SET_set1_EV
      - name: PNRIN_SET_set2_EV
        data_field: PNRIN_SET_set2_EV
      - name: PNRIN_SET_set3_EV
        data_field: PNRIN_SET_set3_EV
      - name: KNRIN_SET_set1_EV
        data_field: KNRIN_SET_set1_EV
      - name: KNRIN_SET_set2_EV
        data_field: KNRIN_SET_set2_EV
      - name: KNRIN_SET_set3_EV
        data_field: KNRIN_SET_set3_EV
      - name: TNCIN_SET_set1_EV
        data_field: TNCIN_SET_set1_EV
      - name: TNCIN_SET_set2_EV
        data_field: TNCIN_SET_set2_EV
      - name: TNCIN_SET_set3_EV
        data_field: TNCIN_SET_set3_EV
      - name: PNROUT_SET_set1_EV
        data_field: PNROUT_SET_set1_EV
      - name: PNROUT_SET_set2_EV
        data_field: PNROUT_SET_set2_EV
      - name: PNROUT_SET_set3_EV
        data_field: PNROUT_SET_set3_EV
      - name: KNROUT_SET_set1_EV
        data_field: KNROUT_SET_set1_EV
      - name: KNROUT_SET_set2_EV
        data_field: KNROUT_SET_set2_EV
      - name: KNROUT_SET_set3_EV
        data_field: KNROUT_SET_set3_EV
      - name: TNCOUT_SET_set1_EV
        data_field: TNCOUT_SET_set1_EV
      - name: TNCOUT_SET_set2_EV
        data_field: TNCOUT_SET_set2_EV
      - name: TNCOUT_SET_set3_EV
        data_field: TNCOUT_SET_set3_EV
  - file_name: othrCrossborderTrips_EV.omx
    tables:
      - name: TAXI_EV
        data_field: TAXI_EV
      - name: TNC_SINGLE_EV
        data_field: TNC_SINGLE_EV
      - name: TNC_SHARED_EV
        data_field: TNC_SHARED_EV
  - file_name: nmCrossborderTrips_EV.omx
    tables:
      - name: WALK_EV
        data_field: WALK_EV
      - name: BIKE_EV
        data_field: BIKE_EV

CONSTANTS:
  trip_c_ivt_base: -0.021
  PERIODS_PER_HOUR: 2
  time_distrib_mean_work: 1.0
  time_distrib_stddEA_work: 0.7
  time_distrib_mean_nonwork: 1.0
  time_distrib_stddEA_nonwork: 0.6
  cost_per_mile_fuel: 12.3  # from parametersByYear.csv, depends on simulation year
  cost_per_mile_maint: 7  # from parametersByYear.csv, depends on simulation year
  work_dist_coef: -8.6
  other_dist_coef: -4.9
  vot_bin_idx_to_skim_label:
    1: L
    2: M
    3: H
  max_walk_time: 60
  taxi_base_fare: 2.20
  taxi_cost_per_mile: 2.30
  taxi_cost_per_minute: 0.10
  tnc_single_base_fare: 2.20
  tnc_single_cost_per_mile: 1.33
  tnc_single_cost_per_minute: 0.24
  tnc_single_cost_minimum: 7.20
  tnc_shared_base_fare: 2.20
  tnc_shared_cost_per_mile: 0.44
  tnc_shared_cost_per_minute: 0.08
  tnc_shared_cost_minimum: 3.00
  tnc_shared_ivt_factor: 1.25
  tnc_single_wait_time_mean_by_density:
    1: 10.3
    2: 8.5
    3: 8.4
    4: 6.3
    5: 4.7
  tnc_single_wait_time_sd_by_density:
    1: 4.1
    2: 4.1
    3: 4.1
    4: 4.1
    5: 4.1
  tnc_shared_wait_time_mean_by_density:
    1: 15.0
    2: 15.0
    3: 11.0
    4: 8.0
    5: 7.0
  tnc_shared_wait_time_sd_by_density:
    1: 4.1
    2: 4.1
    3: 4.1
    4: 4.1
    5: 4.1
  taxi_wait_time_mean_by_density:
    1: 26.5
    2: 17.3
    3: 13.3
    4: 9.5
    5: 5.5
  taxi_wait_time_sd_by_density:
    1: 6.4
    2: 6.4
    3: 6.4
    4: 6.4
    5: 6.4
  wait_time_distribution_by_density_breaks:
    - 500
    - 2000
    - 5000
    - 15000
  trip_c_cost: -0.0003

FINAL_TRIP_COLUMNS:
  - person_id
  - household_id
  - primary_purpose
  - trip_num
  - outbound
  - trip_count
  - destination
  - origin
  - tour_id
  - escort_participants
  - school_escort_direction
  - purpose
  - destination_logsum
  - depart
  - trip_mode
  - mode_choice_logsum
  - vot_da
  - vot_s2
  - vot_s3
  - ownsTransponder
  - parking_zone
  - trip_period
  - tour_participants
  - distance
  - is_ea
  - is_am
  - is_md
  - is_pm
  - is_ev
  - vot1
  - vot2
  - vot3
  - inbound
  - timeDrive
  - distanceDrive
  - costTollDrive
  - timeTransitInVehicle
  - timeRapidTransitInVehicle
  - timeExpressBusTransitInVehicle
  - timeLightRailTransitInVehicle
  - timeCommuterRailTransitInVehicle
  - timeTransitInitialWait
  - costFareTransit
  - transfersTransit
  - sample_rate
  - otaz
  - dtaz
  - model
  - arrival_mode
  - num_participants