# using the same spec for both non-mandatory and joint tours
SPEC: external_non_mandatory_identification.csv
COEFFICIENTS: external_non_mandatory_identification_coefficients.csv

#LOGIT_TYPE: NL
LOGIT_TYPE: MNL

# Adds this column to the persons table and is set to True if workplace is external
EXTERNAL_COL_NAME: is_external_tour
# set to True if not external but CHOOSER_FILTER_COLUMN_NAME is True
INTERNAL_COL_NAME: is_internal_tour

preprocessor:
  SPEC: external_non_mandatory_identification_preprocessor.csv
  DF: df
  TABLES:
    - land_use