SAMPLE_SPEC: external_non_mandatory_destination_sample.csv
SPEC: external_non_mandatory_destination.csv
COEFFICIENTS: external_non_mandatory_destination_coefficients.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: external_non_mandatory

CHOOSER_SEGMENT_COLUMN_NAME: tour_type

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: external_tour_destination_sample

# these segments need to match in the destination size term table
SEGMENTS:
  - shopping
  - othmaint
  - othdiscr
  - eatout
  - social
  - escort

SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - home_zone_id
  - person_id
  - female
  - income
  - income_segment
  - age
  - tour_type_count
  - tour_type_num

LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 14
