
SPEC: external_student_identification.csv
COEFFICIENTS: external_student_identification_coeffs.csv

#LOGIT_TYPE: NL
LOGIT_TYPE: MNL

# boolean column to filter choosers (True means keep)
# will only expose these people to the model
CHOOSER_FILTER_COLUMN_NAME: is_student

# Adds this column to the persons table and is set to True if workplace is external
EXTERNAL_COL_NAME: is_external_student
# set to True if not external but CHOOSER_FILTER_COLUMN_NAME is True
INTERNAL_COL_NAME: is_internal_student