SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - home_zone_id
  - household_id

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 8

DEST_CHOICE_COLUMN_NAME: external_workplace_zone_id
# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if not desired in persons table
DEST_CHOICE_LOGSUM_COLUMN_NAME: external_workplace_location_logsum
# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if not desired in persons table
MODE_CHOICE_LOGSUM_COLUMN_NAME: external_workplace_modechoice_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: external_workplace_location_sample

SAMPLE_SPEC: external_workplace_location.csv
SPEC: external_workplace_location.csv
COEFFICIENTS: external_workplace_location_coefficients.csv

LOGSUM_SETTINGS: tour_mode_choice.yaml
LOGSUM_PREPROCESSOR: nontour_preprocessor

LOGSUM_TOUR_PURPOSE: work

# required by initialize_households when creating workplace_destination_size table
CHOOSER_TABLE_NAME: persons

# size_terms model_selector
MODEL_SELECTOR: external_workplace

# chooser column with segment_id for this segment type
CHOOSER_SEGMENT_COLUMN_NAME: is_external_worker

# boolean column to filter choosers (True means keep)
# CHOOSER_FILTER_COLUMN_NAME: is_worker
CHOOSER_FILTER_COLUMN_NAME: is_external_worker

# FIXME - these are assigned to persons in annotate_persons. we need a better way to manage this
SEGMENT_IDS:
  external_workplace: True  # using only one segment

# model adds these tables (informational - not added if commented out)
# SHADOW_PRICE_TABLE: workplace_shadow_prices
# MODELED_SIZE_TABLE: workplace_modeled_size

# not loaded if commented out
# SAVED_SHADOW_PRICE_TABLE_NAME: workplace_shadow_prices.csv