model_name: resident

output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants
    - vehicles
    - proto_disaggregate_accessibility
    - disaggregate_accessibility

resume_after: write_trip_matrices

models:
  - write_trip_matrices
  - write_to_datalake