
SPEC: transponder_ownership.csv
COEFFICIENTS: transponder_ownership_coefficients.csv

LOGIT_TYPE: MNL

TRANSPONDER_OWNERSHIP_ALT: 1

preprocessor:
  SPEC: transponder_ownership_preprocessor
  DF: df
  TABLES:
    - land_use
    - persons
    - vehicles
