
SPEC: transit_pass_ownership.csv
COEFFICIENTS: transit_pass_ownership_coeffs.csv

#LOGIT_TYPE: NL
LOGIT_TYPE: MNL

preprocessor:
  SPEC: transit_pass_ownership_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - persons