SAMPLE_SPEC: trip_destination_sample.csv
SPEC: trip_destination.csv
COEFFICIENTS: trip_destination_coefficients.csv

SAMPLE_SIZE: 30

DESTINATION_SAMPLE_SPEC: trip_destination_sample.csv
DESTINATION_SPEC: trip_destination.csv

LOGSUM_SETTINGS: trip_mode_choice.yaml

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: trip_destination_sample

# model-specific logsum-related settings
TRIP_ORIGIN: origin
ALT_DEST_COL_NAME: alt_dest
PRIMARY_ORIGIN: tour_leg_origin
PRIMARY_DEST: tour_leg_dest # must be created in preprocessor

# tour_mode is already in trips table, so we don't need it from tours
# (it is assigned in trip_destination_annotate_trips_preprocessor )
REDUNDANT_TOURS_MERGED_CHOOSER_COLUMNS:
  - tour_mode

preprocessor:
  SPEC: trip_destination_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours
    - persons
    - households
    - land_use

# preprocessor for sample, operates on TAZs
alts_preprocessor_sample:
  SPEC: trip_destination_annotate_alts_preprocessor_sample
  DF: alternatives
  TABLES:
    - land_use

# preprocessor for simulate, operates on MAZs in two zone models
# alts_preprocessor_sample:
#   SPEC: trip_destination_annotate_alts_preprocessor_simulate
#   DF: alternatives
#   TABLES:
#     - land_use


# drop failed trips and cleanup failed trip leg_mates for consistency
# (i.e. adjust trip_count, trip_num, first for missing failed trips)
CLEANUP: False

# this setting is used by testing code to force failed trip_destination
# fail_some_trips_for_testing: False
