-- base schemas
EXECUTE [db_meta].[add_xp] 'abm', 'MS_Description', 'Schema to hold and manage ABM data'
EXECUTE [db_meta].[add_xp] 'ref', 'MS_Description', 'Schema to hold and manage lookup and reference tables'
EXECUTE [db_meta].[add_xp] 'dbo', 'MS_Description', 'Workspace and junk default schema for users on small PRIMARY filegroup'
EXECUTE [db_meta].[add_xp] 'abm_staging', 'MS_Description', 'Schema to hold intermediary data tables'
GO


-- abm data tables
EXECUTE [db_meta].[add_xp] 'abm.at_skims', 'SUBSYSTEM', 'AT'
EXECUTE [db_meta].[add_xp] 'abm.at_skims', 'MS_Description', 'Walk and Bike skims in AT model'

EXECUTE [db_meta].[add_xp] 'abm.bike_flow', 'SUBSYSTEM', 'AT'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow', 'MS_Description', 'Bike volumes by roadsegid, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.bike_link', 'SUBSYSTEM', 'AT'
EXECUTE [db_meta].[add_xp] 'abm.bike_link', 'MS_Description', 'SANGIS all streets network used for bike routing and walk access in AT model'

EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab', 'SUBSYSTEM', 'AT'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab', 'MS_Description', 'AB specific attributes of SANGIS all streets network used for bike routing and walk access in AT model'

EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles', 'SUBSYSTEM', 'OTHER'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles', 'MS_Description', 'Number of vehicles in Central Business District MGRAs by time period'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow', 'MS_Description', 'Loaded highway network by hwycov_id, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode', 'MS_Description', 'Loaded highway network by hwycov_id, ab, time period, and mode'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link', 'MS_Description', 'Input highway network, T:\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab', 'MS_Description', 'AB specific attributes of input highway network, T:\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod', 'MS_Description', 'AB and time period specific attributes of input highway network, T:\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod', 'MS_Description', 'Time period specific attributes of input highway network, T:\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_skims', 'SUBSYSTEM', 'HWY'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims', 'MS_Description', 'Loaded highway network skims by origin, destination, and time period'

EXECUTE [db_meta].[add_xp] 'abm.lu_hh', 'SUBSYSTEM', 'LANDUSE'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh', 'MS_Description', 'Synthetic PopSyn households and results of ABM household choice models'

EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input', 'SUBSYSTEM', 'LANDUSE'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input', 'MS_Description', 'MGRA-based input file'

EXECUTE [db_meta].[add_xp] 'abm.lu_person', 'SUBSYSTEM', 'LANDUSE'
EXECUTE [db_meta].[add_xp] 'abm.lu_person', 'MS_Description', 'Synthetic PopSyn persons and results of ABM person choice models'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp', 'SUBSYSTEM', 'LANDUSE'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp', 'MS_Description', 'ABM person free parking model results'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc', 'SUBSYSTEM', 'LANDUSE'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc', 'MS_Description', 'ABM person location choice results'

EXECUTE [db_meta].[add_xp] 'abm.tour_cb', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb', 'MS_Description', 'Cross border model tour list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij', 'MS_Description', 'Individual and joint models tour list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person', 'MS_Description', 'Individual and joint models tour persons list'

EXECUTE [db_meta].[add_xp] 'abm.tour_vis', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis', 'MS_Description', 'Visitor model tour list'

EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow', 'MS_Description', 'Link-based transit flow by mode, access mode, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_flow', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow', 'MS_Description', 'Route and stop based transit flow by mode, access mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_link', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_link', 'MS_Description', 'Transit link input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_onoff', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff', 'MS_Description', 'Route and stop based on/off movements by mode, access mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_pnr', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr', 'MS_Description', 'Park and ride tap lot details and vehicles'

EXECUTE [db_meta].[add_xp] 'abm.transit_route', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_route', 'MS_Description', 'Transit route input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_stop', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop', 'MS_Description', 'Transit stop input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap', 'MS_Description', 'TAP input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skim', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skim', 'MS_Description', 'TAP skims for premium modes by time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk', 'SUBSYSTEM', 'TRANSIT'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk', 'MS_Description', 'TAP walk access'

EXECUTE [db_meta].[add_xp] 'abm.trip_agg', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg', 'MS_Description', 'Trips from aggregate models includes commercial vehicle, EE, E-I, and truck models by origin, destination, purpose, mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.trip_ap', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap', 'MS_Description', 'Trip list from airport model'

EXECUTE [db_meta].[add_xp] 'abm.trip_cb', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb', 'MS_Description', 'Trip list from cross border model'

EXECUTE [db_meta].[add_xp] 'abm.trip_ie', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie', 'MS_Description', 'Trip list from internal-external model'

EXECUTE [db_meta].[add_xp] 'abm.trip_ij', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij', 'MS_Description', 'Trip list from individual and joint models'

EXECUTE [db_meta].[add_xp] 'abm.trip_vis', 'SUBSYSTEM', 'TRIPS AND TOURS'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis', 'MS_Description', 'Trip list from visitor model'
GO


-- ref data tables
EXECUTE [db_meta].[add_xp] 'ref.activity_pattern', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.activity_pattern', 'MS_Description', 'Coordinated Daily Activity Pattern'

EXECUTE [db_meta].[add_xp] 'ref.ap_arrival_mode', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.ap_arrival_mode', 'MS_Description', 'uec\AirportModeChoice.xlsx ("arrival mode")'

EXECUTE [db_meta].[add_xp] 'ref.ap_income_cat', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.ap_income_cat', 'MS_Description', 'uec\AirportModeChoice.xls c_cost Token Descriptions'

EXECUTE [db_meta].[add_xp] 'ref.at_func_class', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.at_func_class', 'MS_Description', 'T:\ABM\AT\working\memos\Draft Bike Network Meta.docx'

EXECUTE [db_meta].[add_xp] 'ref.bike_class', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.bike_class', 'MS_Description', 'T:\ABM\AT\working\memos\Draft Bike Network Meta.docx'

EXECUTE [db_meta].[add_xp] 'ref.educ', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.educ', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.fp_choice', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.fp_choice', 'MS_Description', 'uec\ParkingProvision.xls Alternatives'

EXECUTE [db_meta].[add_xp] 'ref.geography_type', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.geography_type', 'MS_Description', 'Geography type list'

EXECUTE [db_meta].[add_xp] 'ref.geography_zone', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.geography_zone', 'MS_Description', 'IDs and shape attributes for members of geography lists'

EXECUTE [db_meta].[add_xp] 'ref.grade', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.grade', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.hh_income_cat', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.hh_income_cat', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.hisp', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.hisp', 'MS_Description', 'PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.loc_choice', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.loc_choice', 'MS_Description', 'Location choice model type list'

EXECUTE [db_meta].[add_xp] 'ref.loc_choice_segment', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.loc_choice_segment', 'MS_Description', 'uec\AccessibilitiesYYYY.xls (size terms - work), school segment data is hard coded in java and difficult to parse'

EXECUTE [db_meta].[add_xp] 'ref.military', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.military', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.mode', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.mode', 'MS_Description', 'Modes, Cross border tours are odd uec\CrossBorderTourModeChoice.xls Alternatives, Airport trips have a "Passing Through Mode" that does not contribute to regional travel'

EXECUTE [db_meta].[add_xp] 'ref.model_type', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.model_type', 'MS_Description', 'Separate models of the ABM'

EXECUTE [db_meta].[add_xp] 'ref.pemploy', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.pemploy', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.poe', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.poe', 'MS_Description', 'Hardcoded in Java and uec\CrossBorderDestinationChoiceSoaAlternatives2040.csv'

EXECUTE [db_meta].[add_xp] 'ref.pstudent', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.pstudent', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.ptype', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.ptype', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.purpose', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.purpose', 'MS_Description', 'Assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.race', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.race', 'MS_Description', 'PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.scenario', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.scenario', 'MS_Description', 'Loaded scenarios in the database'

EXECUTE [db_meta].[add_xp] 'ref.sex', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.sex', 'MS_Description', 'PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.time_period', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.time_period', 'MS_Description', 'uec\DepartureTimeAndDurationAlternatives.csv and TOD upper limits set in sandag.abm properties'

EXECUTE [db_meta].[add_xp] 'ref.time_resolution', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.time_resolution', 'MS_Description', 'List of time resolutions in ABM model'

EXECUTE [db_meta].[add_xp] 'ref.tour_cat', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.tour_cat', 'MS_Description', 'Tour categories, Added +3 to visitor tour segment and put in this table (0,1) mapped to (3,4)'

EXECUTE [db_meta].[add_xp] 'ref.transit_access_mode', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.transit_access_mode', 'MS_Description', 'Assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.transit_mode', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.transit_mode', 'MS_Description', 'Assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.unit_type', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.unit_type', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'

EXECUTE [db_meta].[add_xp] 'ref.weeks_worked', 'SUBSYSTEM', 'REFERENCE'
EXECUTE [db_meta].[add_xp] 'ref.weeks_worked', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and PUMS Data Dictionary'


-- abm data table columns
EXECUTE [db_meta].[add_xp] 'abm.at_skims.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.skim_id', 'MS_Description', 'Skim type identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.value', 'MS_Description', 'Skim value'

EXECUTE [db_meta].[add_xp] 'abm.bike_flow.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.roadsegid', 'MS_Description', 'SANGIS all streets network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.flow', 'MS_Description', 'Volume on link'

EXECUTE [db_meta].[add_xp] 'abm.bike_link.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.roadsegid', 'MS_Description', 'SANGIS all streets network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.nm', 'MS_Description', 'Name of link'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.at_func_class_id', 'MS_Description', 'Type of road facility'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.bike2sep', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.bike3blvd', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.speed', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.parkarea', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.scenicldx', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.shape', 'MS_Description', 'Line geometry'

EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.roadsegid', 'MS_Description', 'SANGIS all streets network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.from_node', 'MS_Description', 'From node number.'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.to_node', 'MS_Description', 'To node number.'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.gain', 'MS_Description', 'Positive elevation gain in feet'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.bike_class_id', 'MS_Description', 'Bike link classification'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.lanes', 'MS_Description', 'Vehicle lanes present indicator'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.signal', 'MS_Description', 'Indicator of signal at from node'

EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.zone', 'MS_Description', 'Geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.vehicles', 'MS_Description', 'Number of vehicles present'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.flow_pce', 'MS_Description', 'Volume of passenger car equivalent'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.time', 'MS_Description', 'Loaded travel time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.voc', 'MS_Description', 'Volume to capacity ratio'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.v_dist_t', 'MS_Description', 'Vehicle distance'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.vht', 'MS_Description', 'Vehicle hours'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.speed', 'MS_Description', 'Speed calculated as (Length/Time)*60'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.vdf', 'MS_Description', 'Loaded cost (result from link performance function)'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.msa_flow', 'MS_Description', 'Calculated MSA volume'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.msa_time', 'MS_Description', 'Calculated MSA time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.flow', 'MS_Description', 'Total volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.flow', 'MS_Description', 'Total volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.length_mile', 'MS_Description', 'Length of link in miles'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.sphere', 'MS_Description', 'Jurisdiction sphere of influence'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.nm', 'MS_Description', 'Street name'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.cojur', 'MS_Description', 'Count jurisdiction code'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.costat', 'MS_Description', 'Count station number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.coloc', 'MS_Description', 'Indicator if count was taken on this link'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.rloop', 'MS_Description', 'Freeway count station number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.adtlk', 'MS_Description', 'ADT link number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.adtvl', 'MS_Description', 'Observed base year ground count (in hundreds)'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.aspd', 'MS_Description', 'Adjusted link speed'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iyr', 'MS_Description', 'Year the link opened to traffic'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iproj', 'MS_Description', 'Project number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ijur', 'MS_Description', 'Link jurisdiction type'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ifc', 'MS_Description', 'Initial functional classification'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ihov', 'MS_Description', 'Link operation type'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.itruck', 'MS_Description', 'Truck restriction code'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ispd', 'MS_Description', 'Initial posted speed'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iway', 'MS_Description', 'Initial one of two-way operation'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.imed', 'MS_Description', 'Initial median condition'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.shape', 'MS_Description', 'Line geometry'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.from_node', 'MS_Description', 'From node number.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.to_node', 'MS_Description', 'To node number.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.from_nm', 'MS_Description', 'Cross street name at the from end of the link.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.to_nm', 'MS_Description', 'Cross street name at the to end of the link.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.au', 'MS_Description', 'Initial auxilary lanes in from-to direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.pct', 'MS_Description', 'Directional split'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.cnt', 'MS_Description', 'Initial intersection control type at to end'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.cp', 'MS_Description', 'Link capacity'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.cx', 'MS_Description', 'Intersection approach capacity'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.tm', 'MS_Description', 'Link time in minutes in the from-to direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.tx', 'MS_Description', 'Intersection delay time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.ln', 'MS_Description', 'Number of lanes in the "from-to" direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.stm', 'MS_Description', 'Single occupancy vehicle time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.htm', 'MS_Description', 'High occupancy vehicle time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.preload', 'MS_Description', 'Pre-loaded bus volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.hwycov_id', 'MS_Description', 'Highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.ITOLL2', 'MS_Description', 'Link toll cost'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.ITOLL3', 'MS_Description', 'Link toll cost plus auto operating cost'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.ITOLL4', 'MS_Description', 'Link toll cost plus 1.03*auto operating cost applies to LHD and MHD trucks only'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.ITOLL5', 'MS_Description', 'Link toll cost plus 2.33*auto operating cost applies to HHD trucks only'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.ITOLL', 'MS_Description', 'Toll + 100*[01] if managed lane'

EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_drive_alone_toll', 'MS_Description', 'Distance drive alone toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_drive_alone_toll', 'MS_Description', 'Time drive alone toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_drive_alone_toll', 'MS_Description', 'Cost drive alone toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_drive_alone_free', 'MS_Description', 'Distance drive alone'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_drive_alone_free', 'MS_Description', 'Time drive alone'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov2_toll', 'MS_Description', 'Distance shared ride 2 toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov2_toll', 'MS_Description', 'Time shared ride 2 toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_hov2_toll', 'MS_Description', 'Cost shared ride 2 toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov2_free', 'MS_Description', 'Distance shared ride 2'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov2_free', 'MS_Description', 'Time shared ride 2'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov3_toll', 'MS_Description', 'Distance shared ride 3+ toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov3_toll', 'MS_Description', 'Time shared ride 3+ toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_hov3_toll', 'MS_Description', 'Cost shared ride 3+ toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov3_free', 'MS_Description', 'Distance shared ride 3+'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov3_free', 'MS_Description', 'Time shared ride 3+'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_truck_toll', 'MS_Description', 'Distance truck toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_truck_toll', 'MS_Description', 'Time truck toll.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_truck_toll', 'MS_Description', 'Cost truck toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_truck_free', 'MS_Description', 'Distance truck'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_truck_free', 'MS_Description', 'Time truck'

EXECUTE [db_meta].[add_xp] 'abm.lu_hh.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_id', 'MS_Description', 'ABM household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_serial_no', 'MS_Description', 'PUMS household identifier.'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.zone', 'MS_Description', 'Geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_income_cat_id', 'MS_Description', 'Household income category'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_income', 'MS_Description', 'Household income'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.workers', 'MS_Description', 'Number of workers'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.persons', 'MS_Description', 'Number of persons'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.unit_type_id', 'MS_Description', 'PopSyn household unit type'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.autos', 'MS_Description', 'Auto ownership result'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.transponder', 'MS_Description', 'Toll transponder indicator'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.poverty', 'MS_Description', 'Computed poverty level'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.version', 'MS_Description', 'PopSyn version in database'

EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.zone', 'MS_Description', 'Geography reference number'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs', 'MS_Description', 'Housing structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_sf', 'MS_Description', 'Single family structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_mf', 'MS_Description', 'Multi-family structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_mh', 'MS_Description', 'Mobile homes'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh', 'MS_Description', 'Households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_sf', 'MS_Description', 'Single family households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_mf', 'MS_Description', 'Multi-family households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_mh', 'MS_Description', 'Mobile home households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.gq_civ', 'MS_Description', 'Civilian group quarters'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.gq_mil', 'MS_Description', 'Military group quarters'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i1', 'MS_Description', 'Households income group 1'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i2', 'MS_Description', 'Households income group 2'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i3', 'MS_Description', 'Households income group 3'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i4', 'MS_Description', 'Households income group 4'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i5', 'MS_Description', 'Households income group 5'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i6', 'MS_Description', 'Households income group 6'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i7', 'MS_Description', 'Households income group 7'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i8', 'MS_Description', 'Households income group 8'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i9', 'MS_Description', 'Households income group 9'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i10', 'MS_Description', 'Households income group 10'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hhs', 'MS_Description', 'Average household size'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.pop', 'MS_Description', 'Population'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hhp', 'MS_Description', 'Household population'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_ag', 'MS_Description', 'Employment, agriculture'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_const_non_bldg_prod', 'MS_Description', 'Employment, construction production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_const_non_bldg_office', 'MS_Description', 'Employment, construction support'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_utilities_prod', 'MS_Description', 'Employment, utilities production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_utilities_office', 'MS_Description', 'Employment, utilities office'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_mfg_prod', 'MS_Description', 'Employment, manufacturing production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_mfg_office', 'MS_Description', 'Employment, manufacturing office'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_whsle_whs', 'MS_Description', 'Employment, wholesale and warehousing'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_trans', 'MS_Description', 'Employment, transportation activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_retail', 'MS_Description', 'Employment, retail activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_prof_bus_svcs', 'MS_Description', 'Employment, professional and business services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_prof_bus_svcs_bldg_maint', 'MS_Description', 'Employment, professional and business building maintenance'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_ed_k12', 'MS_Description', 'Employment, private education elementary k-12'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_ed_post_k12_oth', 'MS_Description', 'Employment, private education post-secondary'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_health', 'MS_Description', 'Employment, health services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_personal_svcs_office', 'MS_Description', 'Employment, personal services office-based'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_amusement', 'MS_Description', 'Employment, amusement services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_hotel', 'MS_Description', 'Employment, hotels activity (479,480)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_restaurant_bar', 'MS_Description', 'Employment, restaurants and bars'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_personal_svcs_retail', 'MS_Description', 'Employment, personal services retail based'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_religious', 'MS_Description', 'Employment, religious activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_hh', 'MS_Description', 'Employment, private households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_ent', 'MS_Description', 'Employment, state and local government enterprises activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_non_mil', 'MS_Description', 'Employment, federal non-military activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_mil', 'MS_Description', 'Employment, federal military activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_blue', 'MS_Description', 'Employment, state and local government blue collar'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_white', 'MS_Description', 'Employment, state and local government white collar'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_public_ed', 'MS_Description', 'Employment, public education (k-12)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_own_occ_dwell_mgmt', 'MS_Description', 'Employment, owner-occupied dwellings management and maintenance activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_gov_accts', 'MS_Description', 'Employment, federal government accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_st_lcl_gov_accts', 'MS_Description', 'Employment, state and local government accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_cap_accts', 'MS_Description', 'Employment, capital accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_total', 'MS_Description', 'Employment, total'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.enrollgradekto8', 'MS_Description', 'Elementary and middle school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.enrollgrade9to12', 'MS_Description', 'High school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.collegeenroll', 'MS_Description', 'University enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.othercollegeenroll', 'MS_Description', 'Other college enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.adultschenrl', 'MS_Description', 'Adult school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.ech_dist', 'MS_Description', 'Grade school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hch_dist', 'MS_Description', 'High school district'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.pseudomsa', 'MS_Description', 'Pseudo MSA'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.parkarea', 'MS_Description', 'Park area type'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hstallsoth', 'MS_Description', 'Number of hourly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hstallssam', 'MS_Description', 'Number of hourly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hparkcost', 'MS_Description', 'Hourly parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.numfreehrs', 'MS_Description', 'Number of free parking hours available'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dstallsoth', 'MS_Description', 'Number of daily stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dstallssam', 'MS_Description', 'Number of daily stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dparkcost', 'MS_Description', 'Daily parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mstallsoth', 'MS_Description', 'Number of monthly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mstallssam', 'MS_Description', 'Number of monthly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mparkcost', 'MS_Description', 'Monthly parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.totint', 'MS_Description', 'Intersection count in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.duden', 'MS_Description', 'Dwelling unit density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.empden', 'MS_Description', 'Employment density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.popden', 'MS_Description', 'Population density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.retempden', 'MS_Description', 'Retail employment density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.totintbin', 'MS_Description', 'Totint bin (0-80,90-130,130+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.empdenbin', 'MS_Description', 'Empden bin (0-10,11-30,30+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dudenbin', 'MS_Description', 'Duden bin (0-5,5-10,10+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.zip09', 'MS_Description', 'Zip code'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.parkactive', 'MS_Description', 'Park acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.openspaceparkpreserve', 'MS_Description', 'Open space acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.beachactive', 'MS_Description', 'Beach acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.budgetroom', 'MS_Description', 'Budget hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.economyroom', 'MS_Description', 'Economy hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.luxuryroom', 'MS_Description', 'Luxury hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.midpriceroom', 'MS_Description', 'Mid price hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.upscaleroom', 'MS_Description', 'Upscale hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hotelroomtotal', 'MS_Description', 'Total hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.luz_id', 'MS_Description', 'LUZ'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.truckregiontype', 'MS_Description', 'Truck region type'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.district27', 'MS_Description', 'District 27 indicator'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.milestocoast', 'MS_Description', 'Miles to the coast'

EXECUTE [db_meta].[add_xp] 'abm.lu_person.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.hh_id', 'MS_Description', 'ABM household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pnum', 'MS_Description', 'PUMS person number'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.age', 'MS_Description', 'PUMS age'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.sex_id', 'MS_Description', 'PUMS sex'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.military_id', 'MS_Description', 'PopSyn military service code'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pemploy_id', 'MS_Description', 'PopSyn employment type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pstudent_id', 'MS_Description', 'PopSyn student type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.ptype_id', 'MS_Description', 'PopSyn person type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.educ_id', 'MS_Description', 'PUMS SCHL educational attainment'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.grade_id', 'MS_Description', 'PUMS SCHG grade level attending'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.occen5', 'MS_Description', 'PUMS OCCP02/OCCP10 occupation codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.occsoc5', 'MS_Description', 'PUMS SOCP00/SOCP10 occupation codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.indcen', 'MS_Description', 'PUMS INDP02/INDP07 industry codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.weeks_worked_id', 'MS_Description', 'PUMS WKW weeks worked during past 12 months'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.hours_worked', 'MS_Description', 'PUMS WKHP usual hours worked per week during past 12 months'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.race_id', 'MS_Description', 'PUMS race'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.hisp_id', 'MS_Description', 'PUMS hispanic'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.activity_pattern_id', 'MS_Description', 'Chosen activity pattern'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.ie_choice', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.lu_person.version', 'MS_Description', 'PopSyn version in database'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.hh_id', 'MS_Description', 'ABM household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.pnum', 'MS_Description', 'PUMS person number'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.fp_choice_id', 'MS_Description', 'Free parking model choice'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.reimb_pct', 'MS_Description', ''

EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.hh_id', 'MS_Description', 'ABM household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.pnum', 'MS_Description', 'PUMS person number'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.loc_choice_id', 'MS_Description', 'Location choice model identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.loc_choice_segment_id', 'MS_Description', 'Location choice segment identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.zone', 'MS_Description', 'Geography reference number'

EXECUTE [db_meta].[add_xp] 'abm.tour_cb.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.purpose_id', 'MS_Description', 'Tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.start_period_id', 'MS_Description', 'Start time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.end_period_id', 'MS_Description', 'End time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.crossing_mode_id', 'MS_Description', 'Border crossing mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.sentri', 'MS_Description', 'Indicator if SENTRI is available'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.poe_id', 'MS_Description', 'Border crossing port of entry identifier'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.tour_cat_id', 'MS_Description', 'Tour category identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.purpose_id', 'MS_Description', 'Tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.start_period_id', 'MS_Description', 'Start time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.end_period_id', 'MS_Description', 'End time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.mode_id', 'MS_Description', 'Tour mode identifier'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.hh_id', 'MS_Description', 'ABM household identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.pnum', 'MS_Description', 'PUMS person number'

EXECUTE [db_meta].[add_xp] 'abm.tour_vis.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.tour_cat_id', 'MS_Description', 'Tour category identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.purpose_id', 'MS_Description', 'Tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.start_period_id', 'MS_Description', 'Start time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.end_period_id', 'MS_Description', 'End time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.mode_id', 'MS_Description', 'Tour mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.auto_available', 'MS_Description', 'Auto available for tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.hh_income_cat_id', 'MS_Description', 'Household income category'

EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.trcov_id', 'MS_Description', 'Transit network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_mode_id', 'MS_Description', 'Transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_access_mode_id', 'MS_Description', 'Transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.ab', 'MS_Description', 'Link AB indicator'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_flow', 'MS_Description', 'Total transit flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.non_transit_flow', 'MS_Description', 'Total non-transit flow.'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.total_flow', 'MS_Description', 'Total flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.access_walk_flow', 'MS_Description', 'Total walk access flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.xfer_walk_flow', 'MS_Description', 'Total transfer flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.egress_walk_flow', 'MS_Description', 'Total egress flow'

EXECUTE [db_meta].[add_xp] 'abm.transit_flow.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_mode_id', 'MS_Description', 'Transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_access_mode_id', 'MS_Description', 'Transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.route_id', 'MS_Description', 'Transit route identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.from_stop_id', 'MS_Description', 'Transit from stop identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.to_stop_id', 'MS_Description', 'Transit to stop identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.from_mp', 'MS_Description', 'From milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.to_mp', 'MS_Description', 'To milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.baseivtt', 'MS_Description', 'In-vehicle time for transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.cost', 'MS_Description', 'Link cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_flow', 'MS_Description', 'Total transit flow'

EXECUTE [db_meta].[add_xp] 'abm.transit_link.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_link.trcov_id', 'MS_Description', 'Transit network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_link.shape', 'MS_Description', 'Line geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.route_id', 'MS_Description', 'Transit route identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.stop_id', 'MS_Description', 'Transit stop identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_mode_id', 'MS_Description', 'Transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_access_mode_id', 'MS_Description', 'Transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.boardings', 'MS_Description', 'Boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.alightings', 'MS_Description', 'Alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_access_on', 'MS_Description', 'Walk access boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.direct_transfer_on', 'MS_Description', 'Direct access boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_transfer_on', 'MS_Description', 'Walk transfer boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.direct_transfer_off', 'MS_Description', 'Direct transfer alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_transfer_off', 'MS_Description', 'Walk transfer alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.egress_off', 'MS_Description', 'Egress alightings'

EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.tap', 'MS_Description', 'Transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.lot_id', 'MS_Description', 'Lot ID in tap.ptype input file'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.parking_type_id', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.capacity', 'MS_Description', 'Number of stalls in the parking lot'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.distance', 'MS_Description', 'Distance from lot to TAP in feet'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.vehicles', 'MS_Description', 'Number of vehicles parked in lot'

EXECUTE [db_meta].[add_xp] 'abm.transit_route.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.route_id', 'MS_Description', 'Transit route identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.transit_mode_id', 'MS_Description', 'Transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.am_headway', 'MS_Description', 'ABM AM peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.pm_headway', 'MS_Description', 'ABM PM peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.op_headway', 'MS_Description', 'ABM Off-peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.config', 'MS_Description', 'Combination of route, direction, and configuration. XX(X)'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.fare', 'MS_Description', 'Route fare, dollars'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.shape', 'MS_Description', 'Line geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_stop.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.stop_id', 'MS_Description', 'Transit stop identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.route_id', 'MS_Description', 'Transit route identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.trcov_id', 'MS_Description', 'Transit network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.mp', 'MS_Description', 'Milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.near_node', 'MS_Description', 'Nearest node number matches to tnode and trcov_id in trcov/node.'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.fare_zone', 'MS_Description', 'Fare zone for coaster and light rail'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.stop_name', 'MS_Description', 'Stop name'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.shape', 'MS_Description', 'Point geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap.tap', 'MS_Description', 'Transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap.shape', 'MS_Description', 'Point geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.orig_tap', 'MS_Description', 'Origin transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.dest_tap', 'MS_Description', 'Destination transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.init_wait_premium', 'MS_Description', 'Initial wait time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.ivt_premium', 'MS_Description', 'In vehicle time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.walk_time_premium', 'MS_Description', 'Walk time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.transfer_time_premium', 'MS_Description', 'Transfer time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.fare_premium', 'MS_Description', 'Fare premium transit, dollars'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.zone', 'MS_Description', 'Geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.tap', 'MS_Description', 'Transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_boarding_perceived', 'MS_Description', 'Perceived walk time if boarding in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_boarding_actual', 'MS_Description', 'Actual walk time if boarding in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_alighting_perceived', 'MS_Description', 'Perceived walk time if alighting in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_alighting_actual', 'MS_Description', 'Actual walk time if alighting in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.gain_boarding', 'MS_Description', 'Boarding positive elevation gain in feet'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.gain_alighting', 'MS_Description', 'Alighting positive elevation gain in feet'

EXECUTE [db_meta].[add_xp] 'abm.trip_agg.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.trips', 'MS_Description', 'Number of trips'

EXECUTE [db_meta].[add_xp] 'abm.trip_ap.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_id', 'MS_Description', 'Trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.inbound', 'MS_Description', 'Inbound leg of tour Indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.party_size', 'MS_Description', 'Number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_board_tap', 'MS_Description', 'Boarding transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_alight_tap', 'MS_Description', 'Alighting transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_time', 'MS_Description', 'Trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.out_vehicle_time', 'MS_Description', 'Out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_distance', 'MS_Description', 'Trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_cost', 'MS_Description', 'Trip cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.ap_income_cat_id', 'MS_Description', 'Airport model specific synpop income categories'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.nights', 'MS_Description', 'Airport model number of nights of trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.ap_arrival_mode_id', 'MS_Description', 'Airport model arrival mode'

EXECUTE [db_meta].[add_xp] 'abm.trip_cb.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_id', 'MS_Description', 'Trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.inbound', 'MS_Description', 'Inbound leg of tour Indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.party_size', 'MS_Description', 'Number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_board_tap', 'MS_Description', 'Boarding transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_alight_tap', 'MS_Description', 'Alighting transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_time', 'MS_Description', 'Trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.out_vehicle_time', 'MS_Description', 'Out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_distance', 'MS_Description', 'Trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_cost', 'MS_Description', 'Trip cost in dollars'

EXECUTE [db_meta].[add_xp] 'abm.trip_ie.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_id', 'MS_Description', 'Trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.inbound', 'MS_Description', 'Inbound leg of tour Indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.party_size', 'MS_Description', 'Number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_board_tap', 'MS_Description', 'Boarding transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_alight_tap', 'MS_Description', 'Alighting transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_time', 'MS_Description', 'Trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.out_vehicle_time', 'MS_Description', 'Out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_distance', 'MS_Description', 'Trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_cost', 'MS_Description', 'Trip cost in dollars'

EXECUTE [db_meta].[add_xp] 'abm.trip_ij.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_id', 'MS_Description', 'Trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.inbound', 'MS_Description', 'Inbound leg of tour Indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.party_size', 'MS_Description', 'Number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_board_tap', 'MS_Description', 'Boarding transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_alight_tap', 'MS_Description', 'Alighting transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_time', 'MS_Description', 'Trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.out_vehicle_time', 'MS_Description', 'Out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_distance', 'MS_Description', 'Trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_cost', 'MS_Description', 'Trip cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.parking_zone', 'MS_Description', 'Parking zone geography reference number'

EXECUTE [db_meta].[add_xp] 'abm.trip_vis.scenario_id', 'MS_Description', 'Scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.model_type_id', 'MS_Description', 'Model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.tour_id', 'MS_Description', 'Tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_id', 'MS_Description', 'Trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.geography_type_id', 'MS_Description', 'Geography type identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.orig', 'MS_Description', 'Origin geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.dest', 'MS_Description', 'Destination geography reference number'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.time_resolution_id', 'MS_Description', 'Time resolution identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.time_period_id', 'MS_Description', 'Time period identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.mode_id', 'MS_Description', 'Mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.purpose_id', 'MS_Description', 'Trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.inbound', 'MS_Description', 'Inbound leg of tour Indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.party_size', 'MS_Description', 'Number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_board_tap', 'MS_Description', 'Boarding transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_alight_tap', 'MS_Description', 'Alighting transit access point'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_time', 'MS_Description', 'Trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.out_vehicle_time', 'MS_Description', 'Out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_distance', 'MS_Description', 'Trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_cost', 'MS_Description', 'Trip cost in dollars'