-- base schemas
EXECUTE [db_meta].[add_xp] 'abm', 'MS_Description', 'schema to hold and manage ABM data'
EXECUTE [db_meta].[add_xp] 'ref', 'MS_Description', 'schema to hold and manage lookup and reference tables'
EXECUTE [db_meta].[add_xp] 'dbo', 'MS_Description', 'workspace and junk default schema for users on small primary filegroup'
EXECUTE [db_meta].[add_xp] 'abm_staging', 'MS_Description', 'schema to hold intermediary data tables'
GO


-- abm data tables
EXECUTE [db_meta].[add_xp] 'abm.at_skims', 'SUBSYSTEM', 'at'
EXECUTE [db_meta].[add_xp] 'abm.at_skims', 'MS_Description', 'walk and bike skims in at model'

EXECUTE [db_meta].[add_xp] 'abm.bike_flow', 'SUBSYSTEM', 'at'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow', 'MS_Description', 'bike volumes by roadsegid, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.bike_link', 'SUBSYSTEM', 'at'
EXECUTE [db_meta].[add_xp] 'abm.bike_link', 'MS_Description', 'sangis all streets network used for bike routing and walk access in at model'

EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab', 'SUBSYSTEM', 'at'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab', 'MS_Description', 'ab specific attributes of sangis all streets network used for bike routing and walk access in at model'

EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles', 'SUBSYSTEM', 'other'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles', 'MS_Description', 'number of vehicles in central business district mgras by time period'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow', 'MS_Description', 'loaded highway network by hwycov_id, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode', 'MS_Description', 'loaded highway network by hwycov_id, ab, time period, and mode'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link', 'MS_Description', 'input highway network, \\hana\transdata\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab', 'MS_Description', 'ab specific attributes of input highway network, \\hana\trandata\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod', 'MS_Description', 'ab and time period specific attributes of input highway network, \\hana\trandata\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod', 'MS_Description', 'time period specific attributes of input highway network, \\hana\trandata\data\tmodeldoc\TransCAD\metadata'

EXECUTE [db_meta].[add_xp] 'abm.hwy_skims', 'SUBSYSTEM', 'hwy'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims', 'MS_Description', 'loaded highway network skims by origin, destination, and time period'

EXECUTE [db_meta].[add_xp] 'abm.lu_hh', 'SUBSYSTEM', 'land_use'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh', 'MS_Description', 'synthetic popsyn households and results of abm household choice models'

EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input', 'SUBSYSTEM', 'land_use'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input', 'MS_Description', 'mgra based input file'

EXECUTE [db_meta].[add_xp] 'abm.lu_person', 'SUBSYSTEM', 'land_use'
EXECUTE [db_meta].[add_xp] 'abm.lu_person', 'MS_Description', 'synthetic popsyn persons and results of abm person choice models'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp', 'SUBSYSTEM', 'land_use'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp', 'MS_Description', 'abm person free parking model results'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc', 'SUBSYSTEM', 'land_use'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc', 'MS_Description', 'abm person location choice results'

EXECUTE [db_meta].[add_xp] 'abm.tour_cb', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb', 'MS_Description', 'cross border model tour list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ie', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie', 'MS_Description', 'internal-external model tour list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person', 'MS_Description', 'internal-external model tour persons list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij', 'MS_Description', 'individual and joint models tour list'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person', 'MS_Description', 'individual and joint models tour persons list'

EXECUTE [db_meta].[add_xp] 'abm.tour_vis', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis', 'MS_Description', 'visitor model tour list'

EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow', 'MS_Description', 'link based transit flow by mode, access mode, ab, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_flow', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow', 'MS_Description', 'route and stop based transit flow by mode, access mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_link', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_link', 'MS_Description', 'transit link input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_onoff', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff', 'MS_Description', 'route and stop based on and off movements by mode, access mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_pnr', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr', 'MS_Description', 'park and ride tap lot details and vehicles'

EXECUTE [db_meta].[add_xp] 'abm.transit_route', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_route', 'MS_Description', 'transit route input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_stop', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop', 'MS_Description', 'transit stop input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap', 'MS_Description', 'tap input network'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims', 'MS_Description', 'tap skims for premium modes by time period'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk', 'SUBSYSTEM', 'transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk', 'MS_Description', 'tap walk access'

EXECUTE [db_meta].[add_xp] 'abm.trip_agg', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg', 'MS_Description', 'trips from aggregate models includes commercial vehicle, ee, ei, and truck models by origin, destination, purpose, mode, and time period'

EXECUTE [db_meta].[add_xp] 'abm.trip_ap', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap', 'MS_Description', 'trip list from airport model'

EXECUTE [db_meta].[add_xp] 'abm.trip_cb', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb', 'MS_Description', 'trip list from cross border model'

EXECUTE [db_meta].[add_xp] 'abm.trip_ie', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie', 'MS_Description', 'trip list from internal external model'

EXECUTE [db_meta].[add_xp] 'abm.trip_ij', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij', 'MS_Description', 'trip list from individual and joint models'

EXECUTE [db_meta].[add_xp] 'abm.trip_vis', 'SUBSYSTEM', 'trips_tours'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis', 'MS_Description', 'trip list from visitor model'
GO


-- ref data tables
EXECUTE [db_meta].[add_xp] 'ref.activity_pattern', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.activity_pattern', 'MS_Description', 'coordinated daily activity pattern'

EXECUTE [db_meta].[add_xp] 'ref.ap_arrival_mode', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.ap_arrival_mode', 'MS_Description', 'uec\AirportmodeChoice.xlsx ("arrival mode")'

EXECUTE [db_meta].[add_xp] 'ref.ap_income_cat', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.ap_income_cat', 'MS_Description', 'uec\AirportmodeChoice.xls c_cost token descriptions'

EXECUTE [db_meta].[add_xp] 'ref.at_func_class', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.at_func_class', 'MS_Description', '\\hana\transdata\ABM\AT\working\memos\Draft Bike Network Meta.docx'

EXECUTE [db_meta].[add_xp] 'ref.bike_class', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.bike_class', 'MS_Description', '\\hana\transdata\ABM\AT\working\memos\Draft Bike Network Meta.docx'

EXECUTE [db_meta].[add_xp] 'ref.educ', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.educ', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.fp_choice', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.fp_choice', 'MS_Description', 'uec\ParkingProvision.xls alternatives'

EXECUTE [db_meta].[add_xp] 'ref.geography_type', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.geography_type', 'MS_Description', 'geography type list'

EXECUTE [db_meta].[add_xp] 'ref.geography_zone', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.geography_zone', 'MS_Description', 'ids and shape attributes for members of geography lists'

EXECUTE [db_meta].[add_xp] 'ref.grade', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.grade', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.hh_income_cat', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.hh_income_cat', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.hisp', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.hisp', 'MS_Description', 'pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.loc_choice', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.loc_choice', 'MS_Description', 'location choice model type list'

EXECUTE [db_meta].[add_xp] 'ref.loc_choice_segment', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.loc_choice_segment', 'MS_Description', 'uec\AccessibilitiesYYYY.xls (size terms - work), school segment data is hard coded in java and difficult to parse'

EXECUTE [db_meta].[add_xp] 'ref.military', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.military', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.mgra13_xref', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.mgra13_xref', 'MS_Description', 'xref table for series 13 MGRAs'

EXECUTE [db_meta].[add_xp] 'ref.mode', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.mode', 'MS_Description', 'modes, cross border tours are odd uec\CrossBordertourmodeChoice.xls alternatives, airport trips have a "Passing Through mode" that does not contribute to regional travel'

EXECUTE [db_meta].[add_xp] 'ref.model_type', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.model_type', 'MS_Description', 'separate models of the abm'

EXECUTE [db_meta].[add_xp] 'ref.pemploy', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.pemploy', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.poe', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.poe', 'MS_Description', 'hardcoded in Java and uec\CrossBorderDestinationChoiceSoaAlternatives2040.csv'

EXECUTE [db_meta].[add_xp] 'ref.pstudent', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.pstudent', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.ptype', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.ptype', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.purpose', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.purpose', 'MS_Description', 'assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.race', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.race', 'MS_Description', 'pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.taz13_xref', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.taz13_xref', 'MS_Description', 'xref table for series 13 TAZs'

EXECUTE [db_meta].[add_xp] 'ref.scenario', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.scenario', 'MS_Description', 'loaded scenarios in the database'

EXECUTE [db_meta].[add_xp] 'ref.sex', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.sex', 'MS_Description', 'pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.time_period', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.time_period', 'MS_Description', 'uec\DeparturetimeAndDurationAlternatives.csv and tod upper limits set in sandag.abm properties'

EXECUTE [db_meta].[add_xp] 'ref.time_resolution', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.time_resolution', 'MS_Description', 'list of time resolutions in the abm model'

EXECUTE [db_meta].[add_xp] 'ref.tour_cat', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.tour_cat', 'MS_Description', 'tour categories, added +3 to visitor tour segment and put in this table (0,1) mapped to (3,4)'

EXECUTE [db_meta].[add_xp] 'ref.transit_access_mode', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.transit_access_mode', 'MS_Description', 'assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.transit_mode', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.transit_mode', 'MS_Description', 'assigned in SSIS loading package'

EXECUTE [db_meta].[add_xp] 'ref.unit_type', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.unit_type', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'

EXECUTE [db_meta].[add_xp] 'ref.weeks_worked', 'SUBSYSTEM', 'reference'
EXECUTE [db_meta].[add_xp] 'ref.weeks_worked', 'MS_Description', 'create_synhh_synperson.sql in popsyn database and pums data dictionary'
GO


-- abm data table columns
EXECUTE [db_meta].[add_xp] 'abm.at_skims.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.at_skims_id', 'MS_Description', 'at_skims surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.dest_geography_zone_id', 'MS_Description', 'destination geography surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.skim_id', 'MS_Description', 'skim type identifier'
EXECUTE [db_meta].[add_xp] 'abm.at_skims.value', 'MS_Description', 'skim value'

EXECUTE [db_meta].[add_xp] 'abm.bike_flow.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.bike_flow_id', 'MS_Description', 'bike_flow surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.bike_link_ab_id', 'MS_Description', 'bike_link_ab surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_flow.flow', 'MS_Description', 'volume on link'

EXECUTE [db_meta].[add_xp] 'abm.bike_link.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.bike_link_id', 'MS_Description', 'bike_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.roadsegid', 'MS_Description', 'sangis all streets network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.nm', 'MS_Description', 'name of link'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.at_func_class_id', 'MS_Description', 'type of road facility'
EXECUTE [db_meta].[add_xp] 'abm.bike_link.bike2sep', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.bike3blvd', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.speed', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.scenicldx', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.bike_link.shape', 'MS_Description', 'line geometry'

EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.bike_link_ab_id', 'MS_Description', 'bike_link_ab surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.bike_link_id', 'MS_Description', 'bike_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.ab', 'MS_Description', 'link ab indicator'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.from_node', 'MS_Description', 'from node number.'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.to_node', 'MS_Description', 'to node number.'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.gain', 'MS_Description', 'positive elevation gain in feet'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.bike_class_id', 'MS_Description', 'bike link classification'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.lanes', 'MS_Description', 'vehicle lanes present indicator'
EXECUTE [db_meta].[add_xp] 'abm.bike_link_ab.signal', 'MS_Description', 'indicator of signal at from node'

EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.cbd_vehicles_id', 'MS_Description', 'cbd_vehicles surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.geography_zone_id', 'MS_Description', 'geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.cbd_vehicles.vehicles', 'MS_Description', 'number of vehicles present'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.hwy_flow_id', 'MS_Description', 'hwy_flow surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.hwy_link_ab_tod_id', 'MS_Description', 'hwy_flow_ab_tod surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.flow_pce', 'MS_Description', 'volume of passenger car equivalent'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.time', 'MS_Description', 'loaded travel time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.voc', 'MS_Description', 'volume to capacity ratio'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.v_dist_t', 'MS_Description', 'vehicle distance'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.vht', 'MS_Description', 'vehicle hours'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.speed', 'MS_Description', 'dpeed calculated as (length/time)*60'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.vdf', 'MS_Description', 'loaded cost (result from link performance function)'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.msa_flow', 'MS_Description', 'calculated msa volume'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.msa_time', 'MS_Description', 'calculated msa time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow.flow', 'MS_Description', 'total volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.hwy_flow_mode_id', 'MS_Description', 'hwy_flow_mode surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.hwy_flow_id', 'MS_Description', 'hwy_flow surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_flow_mode.flow', 'MS_Description', 'total volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.hwy_link_id', 'MS_Description', 'hwy_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.hwycov_id', 'MS_Description', 'highway network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.length_mile', 'MS_Description', 'length of link in miles'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.sphere', 'MS_Description', 'jurisdiction sphere of influence'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.nm', 'MS_Description', 'street name'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.cojur', 'MS_Description', 'count jurisdiction code'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.costat', 'MS_Description', 'count station number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.coloc', 'MS_Description', 'indicator if count was taken on this link'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.rloop', 'MS_Description', 'freeway count station number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.adtlk', 'MS_Description', 'adt link number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.adtvl', 'MS_Description', 'observed base year ground count (in hundreds)'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.aspd', 'MS_Description', 'adjusted link speed'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iyr', 'MS_Description', 'year the link opened to traffic'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iproj', 'MS_Description', 'project number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ijur', 'MS_Description', 'link jurisdiction type'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ifc', 'MS_Description', 'initial functional classification'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ihov', 'MS_Description', 'link operation type'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.itruck', 'MS_Description', 'truck restriction code'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.ispd', 'MS_Description', 'initial posted speed'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.iway', 'MS_Description', 'initial one or two-way operation'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.imed', 'MS_Description', 'initial median condition'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link.shape', 'MS_Description', 'line geometry'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.hwy_link_ab_id', 'MS_Description', 'hwy_link_ab surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.hwy_link_id', 'MS_Description', 'hwy_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.ab', 'MS_Description', 'link ab indicator'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.from_node', 'MS_Description', 'from node number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.to_node', 'MS_Description', 'to node number'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.from_nm', 'MS_Description', 'cross street name at the from end of the link'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.to_nm', 'MS_Description', 'cross street name at the to end of the link'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.au', 'MS_Description', 'initial auxilary lanes in the from-to direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.pct', 'MS_Description', 'directional split'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab.cnt', 'MS_Description', 'initial intersection control type at to end'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.hwy_link_ab_tod_id', 'MS_Description', 'hwy_link_ab_tod surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.hwy_link_ab_id', 'MS_Description', 'hwy_link_ab surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.hwy_link_tod_id', 'MS_Description', 'hwy_link_tod surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.cp', 'MS_Description', 'link capacity'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.cx', 'MS_Description', 'intersection approach capacity'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.tm', 'MS_Description', 'link time in minutes in the from-to direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.tx', 'MS_Description', 'intersection delay time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.ln', 'MS_Description', 'number of lanes in the from-to direction'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.stm', 'MS_Description', 'single occupancy vehicle time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.htm', 'MS_Description', 'high occupancy vehicle time'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_ab_tod.preload', 'MS_Description', 'pre loaded bus volume'

EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.hwy_link_tod_id', 'MS_Description', 'hwy_link_tod surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.hwy_link_id', 'MS_Description', 'hwy_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.itoll2', 'MS_Description', 'link toll cost'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.itoll3', 'MS_Description', 'link toll cost plus auto operating cost'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.itoll4', 'MS_Description', 'link toll cost plus 1.03*auto operating cost applies to lhd and mhd trucks only'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.itoll5', 'MS_Description', 'link toll cost plus 2.33*auto operating cost applies to hhd trucks only'
EXECUTE [db_meta].[add_xp] 'abm.hwy_link_tod.itoll', 'MS_Description', 'toll + 100*[01] if managed lane'

EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.hwy_skims_id', 'MS_Description', 'hwy_skims surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_drive_alone_toll', 'MS_Description', 'distance drive alone toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_drive_alone_toll', 'MS_Description', 'time drive alone toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_drive_alone_toll', 'MS_Description', 'cost drive alone toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_drive_alone_free', 'MS_Description', 'distance drive alone'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_drive_alone_free', 'MS_Description', 'time drive alone'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov2_toll', 'MS_Description', 'distance shared ride 2 toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov2_toll', 'MS_Description', 'time shared ride 2 toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_hov2_toll', 'MS_Description', 'cost shared ride 2 toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov2_free', 'MS_Description', 'distance shared ride 2'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov2_free', 'MS_Description', 'time shared ride 2'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov3_toll', 'MS_Description', 'distance shared ride 3+ toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov3_toll', 'MS_Description', 'time shared ride 3+ toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_hov3_toll', 'MS_Description', 'cost shared ride 3+ toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_hov3_free', 'MS_Description', 'distance shared ride 3+'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_hov3_free', 'MS_Description', 'time shared ride 3+'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_truck_toll', 'MS_Description', 'distance truck toll'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_truck_toll', 'MS_Description', 'time truck toll.'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.cost_truck_toll', 'MS_Description', 'cost truck toll in dollars'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.dist_truck_free', 'MS_Description', 'distance truck'
EXECUTE [db_meta].[add_xp] 'abm.hwy_skims.time_truck_free', 'MS_Description', 'time truck'

EXECUTE [db_meta].[add_xp] 'abm.lu_hh.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.lu_hh_id', 'MS_Description', 'lu_hh surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_id', 'MS_Description', 'abm household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_serial_no', 'MS_Description', 'pums household identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.geography_zone_id', 'MS_Description', 'geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_income_cat_id', 'MS_Description', 'household income category'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.hh_income', 'MS_Description', 'household income'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.workers', 'MS_Description', 'number of workers'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.persons', 'MS_Description', 'number of persons'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.unit_type_id', 'MS_Description', 'popsyn household unit type'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.autos', 'MS_Description', 'auto ownership result'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.transponder', 'MS_Description', 'toll transponder indicator'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.poverty', 'MS_Description', 'computed poverty level'
EXECUTE [db_meta].[add_xp] 'abm.lu_hh.version', 'MS_Description', 'popsyn version in database'

EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.lu_mgra_input_id', 'MS_Description', 'lu_mgra_input surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_mgra_input.geography_zone_id', 'MS_Description', 'geography_zone surrogate key'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs', 'MS_Description', 'housing structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_sf', 'MS_Description', 'single family structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_mf', 'MS_Description', 'multi family structures'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hs_mh', 'MS_Description', 'mobile homes'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh', 'MS_Description', 'households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_sf', 'MS_Description', 'single family households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_mf', 'MS_Description', 'multi family households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hh_mh', 'MS_Description', 'mobile home households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.gq_civ', 'MS_Description', 'civilian group quarters'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.gq_mil', 'MS_Description', 'military group quarters'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i1', 'MS_Description', 'households income group 1'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i2', 'MS_Description', 'households income group 2'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i3', 'MS_Description', 'households income group 3'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i4', 'MS_Description', 'households income group 4'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i5', 'MS_Description', 'households income group 5'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i6', 'MS_Description', 'households income group 6'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i7', 'MS_Description', 'households income group 7'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i8', 'MS_Description', 'households income group 8'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i9', 'MS_Description', 'households income group 9'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.i10', 'MS_Description', 'households income group 10'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hhs', 'MS_Description', 'average household size'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.pop', 'MS_Description', 'population'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hhp', 'MS_Description', 'household population'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_ag', 'MS_Description', 'employment, agriculture'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_const_non_bldg_prod', 'MS_Description', 'employment, construction production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_const_non_bldg_office', 'MS_Description', 'employment, construction support'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_utilities_prod', 'MS_Description', 'employment, utilities production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_utilities_office', 'MS_Description', 'employment, utilities office'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_mfg_prod', 'MS_Description', 'employment, manufacturing production'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_mfg_office', 'MS_Description', 'employment, manufacturing office'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_whsle_whs', 'MS_Description', 'employment, wholesale and warehousing'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_trans', 'MS_Description', 'employment, transportation activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_retail', 'MS_Description', 'employment, retail activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_prof_bus_svcs', 'MS_Description', 'employment, professional and business services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_prof_bus_svcs_bldg_maint', 'MS_Description', 'employment, professional and business building maintenance'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_ed_k12', 'MS_Description', 'employment, private education elementary k-12'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_ed_post_k12_oth', 'MS_Description', 'employment, private education post secondary'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_health', 'MS_Description', 'employment, health services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_personal_svcs_office', 'MS_Description', 'employment, personal services office based'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_amusement', 'MS_Description', 'employment, amusement services'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_hotel', 'MS_Description', 'employment, hotels activity (479,480)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_restaurant_bar', 'MS_Description', 'employment, restaurants and bars'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_personal_svcs_retail', 'MS_Description', 'employment, personal services retail based'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_religious', 'MS_Description', 'employment, religious activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_pvt_hh', 'MS_Description', 'employment, private households'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_ent', 'MS_Description', 'employment, state and local government enterprises activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_non_mil', 'MS_Description', 'employment, federal non-military activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_mil', 'MS_Description', 'employment, federal military activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_blue', 'MS_Description', 'employment, state and local government blue collar'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_state_local_gov_white', 'MS_Description', 'employment, state and local government white collar'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_public_ed', 'MS_Description', 'employment, public education (k-12)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_own_occ_dwell_mgmt', 'MS_Description', 'employment, owner-occupied dwellings management and maintenance activity'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_fed_gov_accts', 'MS_Description', 'employment, federal government accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_st_lcl_gov_accts', 'MS_Description', 'employment, state and local government accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_cap_accts', 'MS_Description', 'employment, capital accounts'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.emp_total', 'MS_Description', 'employment, total'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.enrollgradekto8', 'MS_Description', 'elementary and middle school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.enrollgrade9to12', 'MS_Description', 'high school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.collegeenroll', 'MS_Description', 'university enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.othercollegeenroll', 'MS_Description', 'other college enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.adultschenrl', 'MS_Description', 'adult school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.ech_dist', 'MS_Description', 'grade school enrollment'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hch_dist', 'MS_Description', 'high school district'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.pseudomsa', 'MS_Description', 'pseudo msa'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.parkarea', 'MS_Description', 'park area type'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hstallsoth', 'MS_Description', 'number of hourly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hstallssam', 'MS_Description', 'number of hourly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hparkcost', 'MS_Description', 'hourly parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.numfreehrs', 'MS_Description', 'number of free parking hours available'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dstallsoth', 'MS_Description', 'number of daily stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dstallssam', 'MS_Description', 'number of daily stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dparkcost', 'MS_Description', 'daily parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mstallsoth', 'MS_Description', 'number of monthly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mstallssam', 'MS_Description', 'number of monthly stalls'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.mparkcost', 'MS_Description', 'monthly parking cost, cents'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.totint', 'MS_Description', 'intersection count in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.duden', 'MS_Description', 'dwelling unit density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.empden', 'MS_Description', 'employment density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.popden', 'MS_Description', 'population density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.retempden', 'MS_Description', 'retail employment density in 1/2 mile radius'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.totintbin', 'MS_Description', 'totint bin (0-80,90-130,130+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.empdenbin', 'MS_Description', 'empden bin (0-10,11-30,30+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.dudenbin', 'MS_Description', 'duden bin (0-5,5-10,10+)'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.zip09', 'MS_Description', 'zip code'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.parkactive', 'MS_Description', 'park acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.openspaceparkpreserve', 'MS_Description', 'open space acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.beachactive', 'MS_Description', 'beach acres'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.budgetroom', 'MS_Description', 'budget hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.economyroom', 'MS_Description', 'economy hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.luxuryroom', 'MS_Description', 'luxury hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.midpriceroom', 'MS_Description', 'mid price hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.upscaleroom', 'MS_Description', 'upscale hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.hotelroomtotal', 'MS_Description', 'total hotel rooms'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.luz_id', 'MS_Description', 'luz'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.truckregiontype', 'MS_Description', 'truck region type'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.district27', 'MS_Description', 'district 27 indicator'
execute [db_meta].[add_xp] 'abm.lu_mgra_input.milestocoast', 'MS_Description', 'miles to the coast'

EXECUTE [db_meta].[add_xp] 'abm.lu_person.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.lu_person_id', 'MS_Description', 'lu_person surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.lu_hh_id', 'MS_Description', 'lu_hh surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pnum', 'MS_Description', 'pums person number'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.age', 'MS_Description', 'pums age'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.sex_id', 'MS_Description', 'pums sex'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.military_id', 'MS_Description', 'popsyn military service code'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pemploy_id', 'MS_Description', 'popsyn employment type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.pstudent_id', 'MS_Description', 'popsyn student type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.ptype_id', 'MS_Description', 'popsyn person type'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.educ_id', 'MS_Description', 'pums SCHl educational attainment'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.grade_id', 'MS_Description', 'pums SCHG grade level attending'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.occen5', 'MS_Description', 'pums OCCP02/OCCP10 occupation codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.occsoc5', 'MS_Description', 'pums SOCP00/SOCP10 occupation codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.indcen', 'MS_Description', 'pums INDP02/INDP07 industry codes'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.weeks_worked_id', 'MS_Description', 'pums WKW weeks worked during past 12 months'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.hours_worked', 'MS_Description', 'pums WKHP usual hours worked per week during past 12 months'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.race_id', 'MS_Description', 'pums race'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.hisp_id', 'MS_Description', 'pums hispanic'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.activity_pattern_id', 'MS_Description', 'chosen activity pattern'
EXECUTE [db_meta].[add_xp] 'abm.lu_person.ie_choice', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.lu_person.version', 'MS_Description', 'popsyn version in database'

EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.lu_person_fp_id', 'MS_Description', 'lu_person_fp surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.lu_person_id', 'MS_Description', 'lu_person surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.fp_choice_id', 'MS_Description', 'Free parking model choice'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_fp.reimb_pct', 'MS_Description', ''

EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.lu_person_lc_id', 'MS_Description', 'lu_person_lc surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.lu_person_id', 'MS_Description', 'lu_person surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.loc_choice_segment_id', 'MS_Description', 'loc_choice_segment surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.lu_person_lc.geography_zone_id', 'MS_Description', 'geography_zone surrogate key'

EXECUTE [db_meta].[add_xp] 'abm.tour_cb.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.tour_cb_id', 'MS_Description', 'tour_cb surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.tour_id', 'MS_Description', 'tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.purpose_id', 'MS_Description', 'tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.start_time_period_id', 'MS_Description', 'start time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.end_time_period_id', 'MS_Description', 'end time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.crossing_mode_id', 'MS_Description', 'border crossing mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.sentri', 'MS_Description', 'indicator if sentri is available'
EXECUTE [db_meta].[add_xp] 'abm.tour_cb.poe_id', 'MS_Description', 'border crossing port of entry identifier'

EXECUTE [db_meta].[add_xp] 'abm.tour_ie.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.tour_ie_id', 'MS_Description', 'tour_ie surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.start_time_period_id', 'MS_Description', 'start time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie.end_time_period_id', 'MS_Description', 'end time_period surrogate key'

EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person.tour_ie_person_id', 'MS_Description', 'tour_ie_person_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person.tour_ie_id', 'MS_Description', 'tour_ie surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ie_person.lu_person_id', 'MS_Description', 'lu_person surrogate key'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.tour_ij_id', 'MS_Description', 'tour_ij surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.tour_id', 'MS_Description', 'tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.tour_cat_id', 'MS_Description', 'tour category identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.purpose_id', 'MS_Description', 'tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.start_time_period_id', 'MS_Description', 'start time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.end_time_period_id', 'MS_Description', 'end time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij.mode_id', 'MS_Description', 'tour mode identifier'

EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.tour_ij_person_id', 'MS_Description', 'tour_ij_person_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.tour_ij_id', 'MS_Description', 'tour_ij surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_ij_person.lu_person_id', 'MS_Description', 'lu_person surrogate key'

EXECUTE [db_meta].[add_xp] 'abm.tour_vis.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.tour_vis_id', 'MS_Description', 'tour_vis surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.tour_id', 'MS_Description', 'tour identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.tour_cat_id', 'MS_Description', 'tour category identifer'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.purpose_id', 'MS_Description', 'tour purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.start_time_period_id', 'MS_Description', 'start time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.end_time_period_id', 'MS_Description', 'end time_period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.mode_id', 'MS_Description', 'tour mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.auto_available', 'MS_Description', 'auto available for tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.tour_vis.hh_income_cat_id', 'MS_Description', 'household income category'

EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_aggflow_id', 'MS_Description', 'transit_aggflow surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_link_id', 'MS_Description', 'transit_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.ab', 'MS_Description', 'link ab indicator'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_mode_id', 'MS_Description', 'transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_access_mode_id', 'MS_Description', 'transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.transit_flow', 'MS_Description', 'total transit flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.non_transit_flow', 'MS_Description', 'total non transit flow.'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.total_flow', 'MS_Description', 'total flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.access_walk_flow', 'MS_Description', 'total walk access flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.xfer_walk_flow', 'MS_Description', 'total transfer flow'
EXECUTE [db_meta].[add_xp] 'abm.transit_aggflow.egress_walk_flow', 'MS_Description', 'total egress flow'

EXECUTE [db_meta].[add_xp] 'abm.transit_flow.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_flow_id', 'MS_Description', 'transit_flow surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_route_id', 'MS_Description', 'transit_route surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.from_transit_stop_id', 'MS_Description', 'from transit_stop surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.to_transit_stop_id', 'MS_Description', 'to transit_stop surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_mode_id', 'MS_Description', 'transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_access_mode_id', 'MS_Description', 'transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.from_mp', 'MS_Description', 'from milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.to_mp', 'MS_Description', 'to milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.baseivtt', 'MS_Description', 'In-vehicle time for transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.cost', 'MS_Description', 'link cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.transit_flow.transit_flow', 'MS_Description', 'total transit flow'

EXECUTE [db_meta].[add_xp] 'abm.transit_link.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_link.transit_link_id', 'MS_Description', 'transit_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_link.trcov_id', 'MS_Description', 'transit network link identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_link.shape', 'MS_Description', 'line geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_onoff_id', 'MS_Description', 'transit_onoff surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_route_id', 'MS_Description', 'transit_route surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_stop_id', 'MS_Description', 'transit_stop surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_mode_id', 'MS_Description', 'transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.transit_access_mode_id', 'MS_Description', 'transit access mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.boardings', 'MS_Description', 'boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.alightings', 'MS_Description', 'alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_access_on', 'MS_Description', 'walk access boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.direct_transfer_on', 'MS_Description', 'direct access boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_transfer_on', 'MS_Description', 'walk transfer boardings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.direct_transfer_off', 'MS_Description', 'direct transfer alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.walk_transfer_off', 'MS_Description', 'walk transfer alightings'
EXECUTE [db_meta].[add_xp] 'abm.transit_onoff.egress_off', 'MS_Description', 'egress alightings'

EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.transit_pnr_id', 'MS_Description', 'transit_pnr surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.transit_tap_id', 'MS_Description', 'transit_tap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.lot_id', 'MS_Description', 'lot ID in tap.ptype input file'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.geography_zone_id', 'MS_Description', 'geography_zone surrogate key, taz where lot is located'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.parking_type_id', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.capacity', 'MS_Description', 'number of stalls in the parking lot'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.distance', 'MS_Description', 'distance from lot to TAP in feet'
EXECUTE [db_meta].[add_xp] 'abm.transit_pnr.vehicles', 'MS_Description', 'number of vehicles parked in lot'

EXECUTE [db_meta].[add_xp] 'abm.transit_route.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.transit_route_id', 'MS_Description', 'transit_route surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.route_id', 'MS_Description', 'transit route identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.transit_mode_id', 'MS_Description', 'transit mode identifer'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.am_headway', 'MS_Description', 'abm am peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.pm_headway', 'MS_Description', 'abm pm peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.op_headway', 'MS_Description', 'abm off peak time period headway'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.nt_headway', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.transit_route.nt_hour', 'MS_Description', ''
EXECUTE [db_meta].[add_xp] 'abm.transit_route.config', 'MS_Description', 'combination of route, direction, and configuration XX(X)'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.fare', 'MS_Description', 'route fare in dollars'
EXECUTE [db_meta].[add_xp] 'abm.transit_route.shape', 'MS_Description', 'line geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_stop.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.transit_stop_id', 'MS_Description', 'transit_stop surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.transit_route_id', 'MS_Description', 'transit_route surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.transit_link_id', 'MS_Description', 'transit_link surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.stop_id', 'MS_Description', 'transit stop identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.mp', 'MS_Description', 'milepost'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.near_node', 'MS_Description', 'nearest node number matches to tnode and trcov_id in trcov/node.'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.fare_zone', 'MS_Description', 'fare zone for coaster and light rail'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.stop_name', 'MS_Description', 'stop name'
EXECUTE [db_meta].[add_xp] 'abm.transit_stop.shape', 'MS_Description', 'point geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap.transit_tap_id', 'MS_Description', 'transit_tap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap.tap', 'MS_Description', 'transit access point'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap.shape', 'MS_Description', 'point geometry'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.transit_tap_skims_id', 'MS_Description', 'transit_tap_skims surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.orig_transit_tap_id', 'MS_Description', 'origin transit_tap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.dest_transit_tap_id', 'MS_Description', 'destination transit_tap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.init_wait_premium', 'MS_Description', 'initial wait time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.ivt_premium', 'MS_Description', 'in vehicle time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.walk_time_premium', 'MS_Description', 'walk time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.transfer_time_premium', 'MS_Description', 'transfer time premium transit'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_skims.fare_premium', 'MS_Description', 'fare premium transit in dollars'

EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.transit_tap_walk_id', 'MS_Description', 'transit_tap_walk surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.geography_zone_id', 'MS_Description', 'geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.transit_tap_id', 'MS_Description', 'transit_tap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_boarding_perceived', 'MS_Description', 'perceived walk time if boarding in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_boarding_actual', 'MS_Description', 'actual walk time if boarding in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_alighting_perceived', 'MS_Description', 'perceived walk time if alighting in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.time_alighting_actual', 'MS_Description', 'actual walk time if alighting in minutes'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.gain_boarding', 'MS_Description', 'boarding positive elevation gain in feet'
EXECUTE [db_meta].[add_xp] 'abm.transit_tap_walk.gain_alighting', 'MS_Description', 'alighting positive elevation gain in feet'

EXECUTE [db_meta].[add_xp] 'abm.trip_agg.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.trip_agg_id', 'MS_Description', 'trip_agg surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_agg.trips', 'MS_Description', 'number of trips'

EXECUTE [db_meta].[add_xp] 'abm.trip_ap.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_ap_id', 'MS_Description', 'trip_ap surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_id', 'MS_Description', 'trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.inbound', 'MS_Description', 'inbound leg of tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.party_size', 'MS_Description', 'number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.board_transit_tap_id', 'MS_Description', 'boarding transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.alight_transit_tap_id', 'MS_Description', 'alighting transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_time', 'MS_Description', 'trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.out_vehicle_time', 'MS_Description', 'out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_distance', 'MS_Description', 'trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.trip_cost', 'MS_Description', 'trip cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.ap_income_cat_id', 'MS_Description', 'airport model specific synpop income categories'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.nights', 'MS_Description', 'airport model number of nights of trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ap.ap_arrival_mode_id', 'MS_Description', 'airport model arrival mode'

EXECUTE [db_meta].[add_xp] 'abm.trip_cb.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_cb_id', 'MS_Description', 'trip_cb surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.tour_cb_id', 'MS_Description', 'tour_cb surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_id', 'MS_Description', 'trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.inbound', 'MS_Description', 'inbound leg of tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.party_size', 'MS_Description', 'number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.board_transit_tap_id', 'MS_Description', 'boarding transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.alight_transit_tap_id', 'MS_Description', 'alighting transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_time', 'MS_Description', 'trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.out_vehicle_time', 'MS_Description', 'out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_distance', 'MS_Description', 'trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_cb.trip_cost', 'MS_Description', 'trip cost in dollars'

EXECUTE [db_meta].[add_xp] 'abm.trip_ie.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_ie_id', 'MS_Description', 'trip_ie surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.model_type_id', 'MS_Description', 'model identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_id', 'MS_Description', 'trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.inbound', 'MS_Description', 'inbound leg of tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.party_size', 'MS_Description', 'number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.board_transit_tap_id', 'MS_Description', 'boarding transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.alight_transit_tap_id', 'MS_Description', 'alighting transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_time', 'MS_Description', 'trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.out_vehicle_time', 'MS_Description', 'out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_distance', 'MS_Description', 'trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ie.trip_cost', 'MS_Description', 'trip cost in dollars'

EXECUTE [db_meta].[add_xp] 'abm.trip_ij.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_ij_id', 'MS_Description', 'trip_ij surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.tour_ij_id', 'MS_Description', 'tour_ij surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_id', 'MS_Description', 'trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.inbound', 'MS_Description', 'inbound leg of tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.party_size', 'MS_Description', 'number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.board_transit_tap_id', 'MS_Description', 'boarding transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.alight_transit_tap_id', 'MS_Description', 'alighting transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_time', 'MS_Description', 'trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.out_vehicle_time', 'MS_Description', 'out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_distance', 'MS_Description', 'trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.trip_cost', 'MS_Description', 'trip cost in dollars'
EXECUTE [db_meta].[add_xp] 'abm.trip_ij.parking_geography_zone_id', 'MS_Description', 'parking geography_zone surrogate key'

EXECUTE [db_meta].[add_xp] 'abm.trip_vis.scenario_id', 'MS_Description', 'scenario identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_vis_id', 'MS_Description', 'trip_vis surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.tour_vis_id', 'MS_Description', 'tour_vis surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_id', 'MS_Description', 'trip identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.orig_geography_zone_id', 'MS_Description', 'origin geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.dest_geography_zone_id', 'MS_Description', 'destination geography_zone surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.time_period_id', 'MS_Description', 'time period surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.mode_id', 'MS_Description', 'mode identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.purpose_id', 'MS_Description', 'trip purpose identifier'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.inbound', 'MS_Description', 'inbound leg of tour indicator'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.party_size', 'MS_Description', 'number of people on trip'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.board_transit_tap_id', 'MS_Description', 'boarding transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.alight_transit_tap_id', 'MS_Description', 'alighting transit_tap_id surrogate key'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_time', 'MS_Description', 'trip time'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.out_vehicle_time', 'MS_Description', 'out of vehicle trip time only applies to transit modes'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_distance', 'MS_Description', 'trip distance'
EXECUTE [db_meta].[add_xp] 'abm.trip_vis.trip_cost', 'MS_Description', 'trip cost in dollars'