-- typical abm user permissions
-- allows for data loading
CREATE ROLE [abm_user]
GRANT CONNECT TO [abm_user]
EXEC sp_addrolemember [db_datareader], [abm_user]
DENY EXECUTE ON OBJECT:: [abm].[sp_shrink_reorg] TO [abm_user]
DENY EXECUTE ON OBJECT:: [abm].[sp_clear_scen] TO [abm_user]
DENY EXECUTE ON OBJECT:: [abm].[sp_del_files] TO [abm_user]
GRANT VIEW DEFINITION ON OBJECT:: [abm].[vi_trip_micro_simul] TO [abm_user]
GRANT VIEW DEFINITION ON OBJECT:: [abm].[vi_tour_micro_simul] TO [abm_user]
GRANT SELECT ON OBJECT:: [db_meta].[data_dictionary] TO [abm_user]
GRANT DELETE ON OBJECT:: [data_load].[scenario_load_request] TO [abm_user]
GRANT INSERT ON OBJECT:: [data_load].[scenario_load_request] TO [abm_user]
GRANT UPDATE ON OBJECT:: [data_load].[scenario_load_request] TO [abm_user]
GRANT EXECUTE ON OBJECT:: [data_load].[sp_request] TO [abm_user]
GRANT EXECUTE ON SCHEMA :: [abm] TO [abm_user]
GRANT SELECT ON SCHEMA :: [abm] TO [abm_user]
GRANT VIEW DEFINITION ON SCHEMA :: [abm] TO [abm_user]
DENY CONTROL ON SCHEMA :: [abm_staging] TO [abm_user]
GRANT ALTER ON SCHEMA :: [emfac] TO [abm_user]
GRANT EXECUTE ON SCHEMA :: [emfac] TO [abm_user]
GRANT SELECT ON SCHEMA :: [emfac] TO [abm_user]
GRANT VIEW DEFINITION ON SCHEMA :: [emfac] TO [abm_user]
GRANT EXECUTE ON SCHEMA :: [rtp_2015] TO [abm_user]
GRANT SELECT ON SCHEMA :: [rtp_2015] TO [abm_user]
GRANT VIEW DEFINITION ON SCHEMA :: [rtp_2015] TO [abm_user]